class DzCommune {
  final String latin;
  final String arabic;
  const DzCommune({required this.latin, required this.arabic});
}

class DzWilaya {
  final String code;
  final String latinName;
  final String arabicName;
  final List<DzCommune> communes;

  const DzWilaya({
    required this.code,
    required this.latinName,
    required this.arabicName,
    required this.communes,
  });
}

const List<DzWilaya> dzWilayasPart1 = [
  DzWilaya(
    code: '01',
    latinName: 'Adrar',
    arabicName: 'أدرار',
    communes: [
      DzCommune(latin: 'Adrar', arabic: 'أدرار'),
      DzCommune(latin: 'Akabli', arabic: 'أقبلي'),
      DzCommune(latin: 'Aoulef', arabic: 'أولف'),
      DzCommune(latin: 'Aougrout', arabic: 'أوقروت'),
      DzCommune(latin: 'Bordj Badji Mokhtar', arabic: 'برج باجي مختار'),
      DzCommune(latin: 'Bouda', arabic: 'بودة'),
      DzCommune(latin: 'Charouine', arabic: 'شروين'),
      DzCommune(latin: 'Deldoul', arabic: 'دلدول'),
      DzCommune(latin: 'Fenoughil', arabic: 'فنوغيل'),
      DzCommune(latin: 'In Zghmir', arabic: 'ان زغمير'),
      DzCommune(latin: 'Ksar Kaddour', arabic: 'قصر قدور'),
      DzCommune(latin: 'Ouled Ahmed Tammi', arabic: 'أولاد أحمد تامي'),
      DzCommune(latin: 'Ouled Aissa', arabic: 'أولاد عيسى'),
      DzCommune(latin: 'Ouled Said', arabic: 'أولاد السعيد'),
      DzCommune(latin: 'Reggane', arabic: 'رقان'),
      DzCommune(latin: 'Sali', arabic: 'سالي'),
      DzCommune(latin: 'Sebaa', arabic: 'السبع'),
      DzCommune(latin: 'Tamekten', arabic: 'تامكتن'),
      DzCommune(latin: 'Tamest', arabic: 'تامست'),
      DzCommune(latin: 'Tamantit', arabic: 'تامنطيط'),
      DzCommune(latin: 'Timimoun', arabic: 'تيميمون'),
      DzCommune(latin: 'Tinerkouk', arabic: 'تڤركوك'),
      DzCommune(latin: 'Tit', arabic: 'تيط'),
      DzCommune(latin: 'Tsabit', arabic: 'تسابيت'),
      DzCommune(latin: 'Zaouiet Kounta', arabic: 'زاوية كنتة'),
    ],
  ),

  DzWilaya(
    code: '02',
    latinName: 'Chlef',
    arabicName: 'الشلف',
    communes: [
      DzCommune(latin: 'Abou El Hassan', arabic: 'أبو الحسن'),
      DzCommune(latin: 'Aïn Merane', arabic: 'عين مران'),
      DzCommune(latin: 'Bénairia', arabic: 'بنايرية'),
      DzCommune(latin: 'Beni Bouateb', arabic: 'بني بوعتاب'),
      DzCommune(latin: 'Beni Haoua', arabic: 'بني حواء'),
      DzCommune(latin: 'Beni Rached', arabic: 'بني راشد'),
      DzCommune(latin: 'Boukadir', arabic: 'بوقادير'),
      DzCommune(latin: 'Bouzeghaia', arabic: 'بوزغاية'),
      DzCommune(latin: 'Breira', arabic: 'بريرة'),
      DzCommune(latin: 'Chlef', arabic: 'الشلف'),
      DzCommune(latin: 'El Hadjadj', arabic: 'الحدّاج'),
      DzCommune(latin: 'El Karimia', arabic: 'الكريمية'),
      DzCommune(latin: 'El Marsa', arabic: 'المرسى'),
      DzCommune(latin: 'Harchoun', arabic: 'حرشون'),
      DzCommune(latin: 'Labiod Medjadja', arabic: 'الأبيض مجاجة'),
      DzCommune(latin: 'Moussadek', arabic: 'مصدق'),
      DzCommune(latin: 'Oued Fodda', arabic: 'وادي الفضة'),
      DzCommune(latin: 'Oued Goussine', arabic: 'وادي قوسين'),
      DzCommune(latin: 'Ouled Abbes', arabic: 'أولاد عباس'),
      DzCommune(latin: 'Ouled Ben Abdelkader', arabic: 'أولاد بن عبد القادر'),
      DzCommune(latin: 'Ouled Fares', arabic: 'أولاد فارس'),
      DzCommune(latin: 'Ouled Sidi Ben Yebka', arabic: 'أولاد سيدي بن يبقى'),
      DzCommune(latin: 'Sendjas', arabic: 'السنجاس'),
      DzCommune(latin: 'Sidi Abderrahmane', arabic: 'سيدي عبد الرحمن'),
      DzCommune(latin: 'Sidi Akkacha', arabic: 'سيدي عكاشة'),
      DzCommune(latin: 'Sidi Assine', arabic: 'سيدي عسين'),
      DzCommune(latin: 'Sidi Bouzid', arabic: 'سيدي بوزيد'),
      DzCommune(latin: 'Sobha', arabic: 'الصبحة'),
      DzCommune(latin: 'Tadjena', arabic: 'تاجنة'),
      DzCommune(latin: 'Talassa', arabic: 'تلعصة'),
      DzCommune(latin: 'Taougrite', arabic: 'تاوقريت'),
      DzCommune(latin: 'Ténès', arabic: 'تنـس'),
      DzCommune(latin: 'Zeboudja', arabic: 'الزبوجة'),
    ],
  ),

  DzWilaya(
    code: '03',
    latinName: 'Laghouat',
    arabicName: 'الأغواط',
    communes: [
      DzCommune(latin: 'Aflou', arabic: 'أفلو'),
      DzCommune(latin: 'Aïn Madhi', arabic: 'عين ماضي'),
      DzCommune(latin: 'Aïn Sidi Ali', arabic: 'عين سيدي علي'),
      DzCommune(latin: 'Benacer Benchohra', arabic: 'بن ناصر بن شهرة'),
      DzCommune(latin: 'Brida', arabic: 'بريدة'),
      DzCommune(latin: 'El Assafia', arabic: 'العسافية'),
      DzCommune(latin: 'El Ghicha', arabic: 'الغيشة'),
      DzCommune(latin: 'El Haouita', arabic: 'الحويطة'),
      DzCommune(latin: 'El Kheneg', arabic: 'الخنق'),
      DzCommune(latin: 'El Ksar', arabic: 'القصر'),
      DzCommune(latin: 'Hadj Mechri', arabic: 'حاج مشري'),
      DzCommune(latin: 'Hassi Delaa', arabic: 'حاسي دلاعة'),
      DzCommune(latin: 'Hassi R\'Mel', arabic: 'حاسي الرمل'),
      DzCommune(latin: 'Ksar El Hirane', arabic: 'قصر الحيران'),
      DzCommune(latin: 'Laghouat', arabic: 'الأغواط'),
      DzCommune(latin: 'Oued M\'Zi', arabic: 'وادي مزي'),
      DzCommune(latin: 'Sebgag', arabic: 'سبقاق'),
      DzCommune(latin: 'Sidi Bouzid', arabic: 'سيدي بوزيد'),
      DzCommune(latin: 'Sidi Makhlouf', arabic: 'سيدي مخلوف'),
      DzCommune(latin: 'Tadjmout', arabic: 'تاجموت'),
      DzCommune(latin: 'Taouila', arabic: 'تاويالة'),
    ],
  ),

  DzWilaya(
    code: '04',
    latinName: 'Oum El Bouaghi',
    arabicName: 'أم البواقي',
    communes: [
      DzCommune(latin: 'Aïn Babouche', arabic: 'عين بابوش'),
      DzCommune(latin: 'Aïn Beïda', arabic: 'عين البيضاء'),
      DzCommune(latin: 'Aïn Diss', arabic: 'عين الديس'),
      DzCommune(latin: 'Aïn Fekroun', arabic: 'عين فكرون'),
      DzCommune(latin: 'Aïn Kercha', arabic: 'عين كرشة'),
      DzCommune(latin: 'Aïn M\'lila', arabic: 'عين مليلة'),
      DzCommune(latin: 'Behir Chergui', arabic: 'بحير الشرقي'),
      DzCommune(latin: 'Berriche', arabic: 'بريش'),
      DzCommune(latin: 'Bir Chouhada', arabic: 'بئر الشهداء'),
      DzCommune(latin: 'Dhalaa', arabic: 'الضلعة'),
      DzCommune(latin: 'El Amiria', arabic: 'العامرية'),
      DzCommune(latin: 'El Belala', arabic: 'البلالة'),
      DzCommune(latin: 'El Djazia', arabic: 'الجازية'),
      DzCommune(
        latin: 'El Fedjoudj Boughrara Saoudi',
        arabic: 'الفجوج بوقرارة سعودي',
      ),
      DzCommune(latin: 'El Harmilia', arabic: 'الحرملية'),
      DzCommune(latin: 'El Mekhatria', arabic: 'المicaطرية'),
      DzCommune(latin: 'El Oueldja', arabic: 'الولجة'),
      DzCommune(latin: 'Fkirina', arabic: 'فكيرينة'),
      DzCommune(latin: 'Hanchir Toumghani', arabic: 'هنشير تومغني'),
      DzCommune(latin: 'Ksar Sbahi', arabic: 'قصر صباحي'),
      DzCommune(latin: 'Meskiana', arabic: 'مسكيانة'),
      DzCommune(latin: 'Oued Nini', arabic: 'وادي نيني'),
      DzCommune(latin: 'Ouled Gacem', arabic: 'أولاد ڤاسم'),
      DzCommune(latin: 'Ouled Hamla', arabic: 'أولاد حملة'),
      DzCommune(latin: 'Ouled Zouai', arabic: 'أولاد زواي'),
      DzCommune(latin: 'Rahia', arabic: 'الراحية'),
      DzCommune(latin: 'Souk Naamane', arabic: 'سوق نعمان'),
      DzCommune(latin: 'Zorg', arabic: 'زرق'),
      DzCommune(latin: 'Zouabi', arabic: 'زوابي'),
    ],
  ),

  DzWilaya(
    code: '05',
    latinName: 'Batna',
    arabicName: 'باتنة',
    communes: [
      DzCommune(latin: 'Aïn Djasser', arabic: 'عين جاسر'),
      DzCommune(latin: 'Aïn Touta', arabic: 'عين التوتة'),
      DzCommune(latin: 'Arris', arabic: 'آريس'),
      DzCommune(latin: 'Barika', arabic: 'بريكة'),
      DzCommune(latin: 'Batna', arabic: 'باتنة'),
      DzCommune(latin: 'Ben Foudhala El Hakania', arabic: 'بن فوضالة الحكانية'),
      DzCommune(latin: 'Bitam', arabic: 'بيطام'),
      DzCommune(latin: 'Boumia', arabic: 'بومية'),
      DzCommune(latin: 'Bouzina', arabic: 'بوزينة'),
      DzCommune(latin: 'Chemora', arabic: 'الشمرة'),
      DzCommune(latin: 'Chir', arabic: 'شير'),
      DzCommune(latin: 'Djerma', arabic: 'جرمة'),
      DzCommune(latin: 'El Hassi', arabic: 'الحاسي'),
      DzCommune(latin: 'El Madher', arabic: 'المعذر'),
      DzCommune(latin: 'Fesdis', arabic: 'فِسديس'),
      DzCommune(latin: 'Ghassira', arabic: 'غسيرة'),
      DzCommune(latin: 'Gosbat', arabic: 'قصدير؟'), // à valider
      DzCommune(latin: 'Guigba', arabic: 'قيقبة'),
      DzCommune(latin: 'Hidoussa', arabic: 'حيدوسة'),
      DzCommune(latin: 'Ichmoul', arabic: 'إشمول'),
      DzCommune(latin: 'Inoughissen', arabic: 'إينوغيسن'),
      DzCommune(latin: 'Kimmel', arabic: 'كيميل'),
      DzCommune(latin: 'Ksar Bellezma', arabic: 'قصر بلزمة'),
      DzCommune(latin: 'Lemcene', arabic: 'لمسان'),
      DzCommune(latin: 'Merouana', arabic: 'مروانة'),
      DzCommune(latin: 'Menaa', arabic: 'منعة'),
      DzCommune(latin: 'N\'Gaous', arabic: 'نقاوس'),
      DzCommune(latin: 'Oued Chaaba', arabic: 'وادي الشعبة'),
      DzCommune(latin: 'Oued El Ma', arabic: 'وادي الماء'),
      DzCommune(latin: 'Oued Taga', arabic: 'وادي الطاقة'),
      DzCommune(latin: 'Ouled Ammar', arabic: 'أولاد عمار'),
      DzCommune(latin: 'Ouled Fadel', arabic: 'أولاد فاضل'),
      DzCommune(latin: 'Ouled Sellam', arabic: 'أولاد سلام'),
      DzCommune(latin: 'Ouled Si Slimane', arabic: 'أولاد سي سليمان'),
      DzCommune(latin: 'Rahbat', arabic: 'الراحة؟'), // à valider
      DzCommune(latin: 'Sefiane', arabic: 'سفيان'),
      DzCommune(latin: 'Seggana', arabic: 'سقانة'),
      DzCommune(latin: 'Seriana', arabic: 'سريانة'),
      DzCommune(latin: 'T\'Kout', arabic: 'تكوت'),
      DzCommune(latin: 'Tazoult', arabic: 'تازولت'),
      DzCommune(latin: 'Taxlent', arabic: 'تاكسلنت'),
      DzCommune(latin: 'Tigharghar', arabic: 'تيغرقَر'),
      DzCommune(latin: 'Tilatou', arabic: 'تيلاطو'),
      DzCommune(latin: 'Timgad', arabic: 'تيمقاد'),
      DzCommune(latin: 'Zanet El Beida', arabic: 'زانة البيضاء'),
    ],
  ),
];

const List<DzWilaya> dzWilayasPart2 = [
  // 06 — Béjaïa
  DzWilaya(
    code: '06',
    latinName: 'Béjaïa',
    arabicName: 'بجاية',
    communes: [
      DzCommune(latin: 'Adekar', arabic: 'أدكار'),
      DzCommune(latin: 'Akbou', arabic: 'أقبو'),
      DzCommune(latin: 'Akfadou', arabic: 'أكفادو'),
      DzCommune(latin: 'Amalou', arabic: 'أمالو'),
      DzCommune(latin: 'Amizour', arabic: 'أميزور'),
      DzCommune(latin: 'Aokas', arabic: 'أوقاس'),
      DzCommune(latin: 'Barbacha', arabic: 'برباشة'),
      DzCommune(latin: 'Béjaïa', arabic: 'بجاية'),
      DzCommune(latin: 'Beni Djellil', arabic: 'بني جليل'),
      DzCommune(latin: 'Beni Ksila', arabic: 'بني كسيلة'),
      DzCommune(latin: 'Beni Maouche', arabic: 'بني معوش'),
      DzCommune(latin: 'Beni Mellikeche', arabic: 'بني مليكش'),
      DzCommune(latin: 'Boukhelifa', arabic: 'بوخليفة'),
      DzCommune(latin: 'Chellata', arabic: 'شلاطة'),
      DzCommune(latin: 'Chemini', arabic: 'شميني'),
      DzCommune(latin: 'Darguina', arabic: 'درقينة'),
      DzCommune(latin: 'Draâ El Caïd', arabic: 'ذراع القايد'),
      DzCommune(latin: 'El Kseur', arabic: 'القصر'),
      DzCommune(latin: 'Fenaïa Ilmaten', arabic: 'فناية إلماتن'),
      DzCommune(latin: 'Ighil Ali', arabic: 'إغيل علي'),
      DzCommune(latin: 'Ighram', arabic: 'إغرم'),
      DzCommune(latin: 'Kendira', arabic: 'قنديرة'),
      DzCommune(latin: 'Kherrata', arabic: 'خراطة'),
      DzCommune(latin: 'M\'cisna', arabic: 'مسيسنة'),
      DzCommune(latin: 'Melbou', arabic: 'ملبو'),
      DzCommune(latin: 'Oued Ghir', arabic: 'وادي غير'),
      DzCommune(latin: 'Ouzellaguen', arabic: 'أوزلاقن'),
      DzCommune(latin: 'Seddouk', arabic: 'صدوق'),
      DzCommune(latin: 'Sidi Aïch', arabic: 'سيدي عيش'),
      DzCommune(latin: 'Sidi Ayad', arabic: 'سيدي عياد'),
      DzCommune(latin: 'Souk El Tenine', arabic: 'سوق الاثنين'),
      DzCommune(latin: 'Tala Hamza', arabic: 'تالة حمزة'),
      DzCommune(latin: 'Tamokra', arabic: 'تمقرة'),
      DzCommune(latin: 'Taskriout', arabic: 'تسكريوت'),
      DzCommune(latin: 'Tazmalt', arabic: 'تازمالت'),
      DzCommune(latin: 'Tibane', arabic: 'تيبان'),
      DzCommune(latin: 'Tichy', arabic: 'تيشي'),
      DzCommune(latin: 'Tifra', arabic: 'تيفرة'),
      DzCommune(latin: 'Timezrit', arabic: 'تيمزريت'),
      DzCommune(latin: 'Tinebdar', arabic: 'تينبذار'),
      DzCommune(latin: 'Tizi N\'Berber', arabic: 'تيزي نبربر'),
      DzCommune(latin: 'Aït Smail', arabic: 'آيت إسماعيل'),
      DzCommune(latin: 'Taourirt Ighil', arabic: 'تاوريرت إغيل'),
    ],
  ),

  // 07 — Biskra
  DzWilaya(
    code: '07',
    latinName: 'Biskra',
    arabicName: 'بسكرة',
    communes: [
      DzCommune(latin: 'Aïn Naga', arabic: 'عين ناقة'),
      DzCommune(latin: 'Aïn Zaatout', arabic: 'عين زعطوط'),
      DzCommune(latin: 'Biskra', arabic: 'بسكرة'),
      DzCommune(latin: 'Bordj Ben Azzouz', arabic: 'برج بن عزوز'),
      DzCommune(latin: 'Bouchagroun', arabic: 'بوشقرون'),
      DzCommune(latin: 'Branis', arabic: 'برانيس'),
      DzCommune(latin: 'Chetma', arabic: 'شتمة'),
      DzCommune(latin: 'Djemorah', arabic: 'جمورة'),
      DzCommune(latin: 'El Feidh', arabic: 'الفيض'),
      DzCommune(latin: 'El Ghrous', arabic: 'الغروس'),
      DzCommune(latin: 'El Hadjeb', arabic: 'الحاجب'),
      DzCommune(latin: 'El Haouch', arabic: 'الحوش'),
      DzCommune(latin: 'El Kantara', arabic: 'القنطرة'),
      DzCommune(latin: 'El Outaya', arabic: 'الوطاية'),
      DzCommune(latin: 'Foughala', arabic: 'فوغالة'),
      DzCommune(latin: 'Khenguet Sidi Nadji', arabic: 'خنقة سيدي ناجي'),
      DzCommune(latin: 'Lichana', arabic: 'ليشانه'),
      DzCommune(latin: 'Lioua', arabic: 'ليوة'),
      DzCommune(latin: 'M’Chouneche', arabic: 'مشيونش'),
      DzCommune(latin: 'Meziraa', arabic: 'ميزرة'),
      DzCommune(latin: 'Ourlal', arabic: 'أورلال'),
      DzCommune(latin: 'Oumache', arabic: 'أوماش'),
      DzCommune(latin: 'Sidi Okba', arabic: 'سيدي عقبة'),
      DzCommune(latin: 'Tolga', arabic: 'طولقة'),
      DzCommune(latin: 'Zeribet El Oued', arabic: 'زريبة الوادي'),
    ],
  ),

  // 08 — Béchar
  DzWilaya(
    code: '08',
    latinName: 'Béchar',
    arabicName: 'بشار',
    communes: [
      DzCommune(latin: 'Abadla', arabic: 'العبادلة'),
      DzCommune(latin: 'Béchar', arabic: 'بشار'),
      DzCommune(latin: 'Beni Ounif', arabic: 'بني ونيف'),
      DzCommune(latin: 'Boukais', arabic: 'بوكايس'),
      DzCommune(latin: 'El Ouata', arabic: 'العواطة'),
      DzCommune(latin: 'Erg Ferradj', arabic: 'عرق فراج'),
      DzCommune(latin: 'Igli', arabic: 'إقلي'),
      DzCommune(latin: 'Kenadsa', arabic: 'قنادسة'),
      DzCommune(latin: 'Ksabi', arabic: 'القصابي'),
      DzCommune(latin: 'Lahmar', arabic: 'الأحمر'),
      DzCommune(
        latin: 'Mechraa Houari Boumediene',
        arabic: 'مشرع هواري بومدين',
      ),
      DzCommune(latin: 'Meridja', arabic: 'المريجة'),
      DzCommune(latin: 'Mogheul', arabic: 'موغيل'),
      DzCommune(latin: 'Taghit', arabic: 'تاغيت'),
      DzCommune(latin: 'Tamtert', arabic: 'تامترت'),
      DzCommune(latin: 'Beni Ikhlef', arabic: 'بني إخلف'),
      DzCommune(latin: 'El Bnoud', arabic: 'البنود'),
    ],
  ),

  // 09 — Blida
  DzWilaya(
    code: '09',
    latinName: 'Blida',
    arabicName: 'البليدة',
    communes: [
      DzCommune(latin: 'Blida', arabic: 'البليدة'),
      DzCommune(latin: 'Beni Mered', arabic: 'بني مراد'),
      DzCommune(latin: 'Bouarfa', arabic: 'بوعرفة'),
      DzCommune(latin: 'Boufarik', arabic: 'بوفاريك'),
      DzCommune(latin: 'Bouinan', arabic: 'بوعينان'),
      DzCommune(latin: 'Bougara', arabic: 'بوقرة'),
      DzCommune(latin: 'Chebli', arabic: 'الشبلي'),
      DzCommune(latin: 'Chiffa', arabic: 'الشفة'),
      DzCommune(latin: 'Chréa', arabic: 'الشريعة'),
      DzCommune(latin: 'El Affroun', arabic: 'العفرون'),
      DzCommune(latin: 'Guerrouaou', arabic: 'قرواو'),
      DzCommune(latin: 'Hammam Melouane', arabic: 'حمام ملوان'),
      DzCommune(
        latin: 'Larbaâ',
        arabic: 'العفرون؟/الأربعاء',
      ), // selon source: "الأربعاء"
      DzCommune(latin: 'Meftah', arabic: 'مفتاح'),
      DzCommune(latin: 'Mouzaïa', arabic: 'موزاية'),
      DzCommune(latin: 'Oued El Alleug', arabic: 'وادي العلايق'),
      DzCommune(latin: 'Ouled Slama', arabic: 'أولاد سلامة'),
      DzCommune(latin: 'Soumaa', arabic: 'الصومعة'),
      DzCommune(latin: 'Aïn Romana', arabic: 'عين romana'),
      DzCommune(latin: 'Beni Tamou', arabic: 'بني تامو'),
      DzCommune(latin: 'Benkhelil', arabic: 'بن خليل'),
      DzCommune(latin: 'Djebabra', arabic: 'جبابرة'),
    ],
  ),

  // 10 — Bouira
  DzWilaya(
    code: '10',
    latinName: 'Bouira',
    arabicName: 'البويرة',
    communes: [
      DzCommune(latin: 'Bouira', arabic: 'البويرة'),
      DzCommune(latin: 'Aïn Bessem', arabic: 'عين بسام'),
      DzCommune(latin: 'Aïn Laloui', arabic: 'عين لالوي'),
      DzCommune(latin: 'Aghbalou', arabic: 'أغبالو'),
      DzCommune(latin: 'Aïn El Hadjar', arabic: 'عين الحجر'),
      DzCommune(latin: 'Aïn El Turk', arabic: 'عين الترك'),
      DzCommune(latin: 'Bechloul', arabic: 'بشلول'),
      DzCommune(latin: 'Bir Ghbalou', arabic: 'بير غبالو'),
      DzCommune(latin: 'Bordj Okhriss', arabic: 'برج أوخريص'),
      DzCommune(latin: 'Djebahia', arabic: 'جباحية'),
      DzCommune(latin: 'Dirah', arabic: 'ديرة'),
      DzCommune(latin: 'El Adjiba', arabic: 'العجيبة'),
      DzCommune(latin: 'El Asnam', arabic: 'الأصنام'),
      DzCommune(latin: 'El Hachimia', arabic: 'الهاشمية'),
      DzCommune(latin: 'El Hakimia', arabic: 'الحكيمية'),
      DzCommune(latin: 'El Hammam', arabic: 'الحمام'),
      DzCommune(latin: 'Haizer', arabic: 'حيزر'),
      DzCommune(latin: 'Hanacha', arabic: 'حناشة'),
      DzCommune(latin: 'Kadiria', arabic: 'القادرية'),
      DzCommune(latin: 'Lakhdaria', arabic: 'الأخضرية'),
      DzCommune(latin: 'M\'Chedallah', arabic: 'مشدا الله'),
      DzCommune(latin: 'Maala', arabic: 'معالة'),
      DzCommune(latin: 'Oued El Berdi', arabic: 'وادي البردي'),
      DzCommune(latin: 'Raouraoua', arabic: 'روراوة'),
      DzCommune(latin: 'Saharidj', arabic: 'الصهايجة'),
      DzCommune(latin: 'Sour El Ghozlane', arabic: 'سور الغزلان'),
      DzCommune(latin: 'Taghzout', arabic: 'تاغزوت'),
      DzCommune(latin: 'Taguedit', arabic: 'تاقديت'),
      DzCommune(latin: 'Souk El Khemis', arabic: 'سوق الخميس'),
      DzCommune(latin: 'Z\'barbar', arabic: 'زبربر'),
    ],
  ),
];

const List<DzWilaya> dzWilayasPart3 = [
  // 11 — Tamanrasset (بعد 2019/2021 : In Salah & In Guezzam sont devenues des wilayas distinctes)
  DzWilaya(
    code: '11',
    latinName: 'Tamanrasset',
    arabicName: 'تمنراست',
    communes: [
      DzCommune(latin: 'Tamanrasset', arabic: 'تمنراست'),
      DzCommune(latin: 'Abalessa', arabic: 'أبالسة'),
      DzCommune(latin: 'Idles', arabic: 'إدلس'),
      DzCommune(latin: 'In Amguel', arabic: 'عين أمقل'),
      DzCommune(latin: 'Tazrouk', arabic: 'تاظروك'),
    ],
  ),

  // 12 — Tébessa
  DzWilaya(
    code: '12',
    latinName: 'Tébessa',
    arabicName: 'تبسة',
    communes: [
      DzCommune(latin: 'Tébessa', arabic: 'تبسة'),
      DzCommune(latin: 'Bir El Ater', arabic: 'بئر العاتر'),
      DzCommune(latin: 'El Aouinet', arabic: 'العوينات'),
      DzCommune(latin: 'Cheria', arabic: 'الشريعة'),
      DzCommune(latin: 'Morsott', arabic: 'مرسط'),
      DzCommune(latin: 'El Kouif', arabic: 'الكويف'),
      DzCommune(latin: 'Negrine', arabic: 'نقرين'),
      DzCommune(latin: 'Bir Dheheb', arabic: 'بئر الذهب'),
      DzCommune(latin: 'El Ogla', arabic: 'الأقلى'),
      DzCommune(latin: 'El Ogla El Malha', arabic: 'الأقلى المالحة'),
      DzCommune(latin: 'Ouenza', arabic: 'الونزة'),
      DzCommune(
        latin: 'El Ma El Abiodh',
        arabic: 'الماء الأبيض',
      ), // parfois écrit "El Malabiod"
      DzCommune(latin: 'Oum Ali', arabic: 'أم علي'),
      DzCommune(
        latin: 'Guorriguer',
        arabic: 'ڤوريڤير',
      ), // TODO(AR): translittération locale
      DzCommune(latin: 'Bedjene', arabic: 'بجن'), // TODO(AR)
      DzCommune(latin: 'El Meridj', arabic: 'المريدج'),
      DzCommune(latin: 'Bekkaria', arabic: 'البكارية'),
      DzCommune(latin: 'Boulhaf Dyr', arabic: 'بولحف دير'),
      DzCommune(latin: 'Aïn Zerga', arabic: 'عين الزرڨة'),
      DzCommune(
        latin: 'Oued Zitoun',
        arabic: 'وادي الزيتون',
      ), // parfois rattachée à El Tarf ; ici liste locale
      DzCommune(latin: 'Hammamet', arabic: 'حمامات'),
      DzCommune(latin: 'El Houidjbet', arabic: 'الحويجبات'),
      DzCommune(latin: 'Safsaf El Ouesra', arabic: 'صفصاف الوسرى'),
      DzCommune(latin: 'Bekkaria', arabic: 'البكارية'),
      DzCommune(latin: 'Tlidjene', arabic: 'تليجن'),
      DzCommune(
        latin: 'Aïn Kerma',
        arabic: 'عين كرمة',
      ), // TODO(AR): vérifier si incluse localement
      DzCommune(
        latin: 'El Ma Labiod',
        arabic: 'الماء الأبيض',
      ), // doublon sécurisé
    ],
  ),

  // 13 — Tlemcen
  DzWilaya(
    code: '13',
    latinName: 'Tlemcen',
    arabicName: 'تلمسان',
    communes: [
      DzCommune(latin: 'Tlemcen', arabic: 'تلمسان'),
      DzCommune(latin: 'Mansourah', arabic: 'منصورة'),
      DzCommune(latin: 'Chetouane', arabic: 'شتوان'),
      DzCommune(latin: 'Beni Mester', arabic: 'بني مستر'),
      DzCommune(latin: 'Sabra', arabic: 'صبرا'),
      DzCommune(latin: 'Remchi', arabic: 'الرمشي'),
      DzCommune(latin: 'Hennaya', arabic: 'هنين'),
      DzCommune(latin: 'Maghnia', arabic: 'مغنية'),
      DzCommune(latin: 'Souk Tleta', arabic: 'سوق الثلاثاء'),
      DzCommune(latin: 'Aïn Youcef', arabic: 'عين يوسف'),
      DzCommune(latin: 'Sebdou', arabic: 'سبدو'),
      DzCommune(latin: 'Beni Snous', arabic: 'بني سنوس'),
      DzCommune(latin: 'Nedroma', arabic: 'نَدْرُومة'),
      DzCommune(latin: 'Ghazaouet', arabic: 'الغزوات'),
      DzCommune(latin: 'Honaine', arabic: 'هنين'),
      DzCommune(latin: 'Beni Boussaid', arabic: 'بني بوسعيد'),
      DzCommune(latin: 'Bab El Assa', arabic: 'باب العسة'),
      DzCommune(latin: 'Souani', arabic: 'سواني'),
      DzCommune(latin: 'Sidi Djillali', arabic: 'سيدي الجيلالي'),
      DzCommune(latin: 'Bensekrane', arabic: 'بن سكران'),
      DzCommune(latin: 'Aïn Talout', arabic: 'عين تالوت'),
      DzCommune(latin: 'Ouled Mimoun', arabic: 'أولاد ميمون'),
      DzCommune(latin: 'El Gor', arabic: 'القور'),
      DzCommune(latin: 'Terny Beni Hediel', arabic: 'ترني بني هديل'),
      DzCommune(latin: 'Sidi Abdelli', arabic: 'سيدي عبد اللي'),
      DzCommune(latin: 'Sidi Medjahed', arabic: 'سيدي مجاهد'),
      DzCommune(latin: 'Fellaoucene', arabic: 'فلاوسن'),
      DzCommune(
        latin: 'Mansourah (rurale)',
        arabic: 'منصورة (ريفية)',
      ), // pour éviter confusion
      DzCommune(latin: 'Ouled Riyah', arabic: 'أولاد رياح'),
      DzCommune(latin: 'Sabra (rurale)', arabic: 'صبرا (ريفية)'),
      DzCommune(latin: 'Zenata', arabic: 'زناتة'),
      DzCommune(latin: 'Hammam Boughrara', arabic: 'حمام بوغرارة'),
      DzCommune(latin: 'Sidi Boumediene', arabic: 'سيدي بومدين'),
      DzCommune(latin: 'Sidi Bou Chehar', arabic: 'سيدي أبو شاهر'), // TODO(AR)
      DzCommune(latin: 'Aïn Fezza', arabic: 'عين فزة'),
      DzCommune(latin: 'Aïn Fetah', arabic: 'عين فتاح'),
      DzCommune(latin: 'Aïn Ghoraba', arabic: 'عين الغرابة'),
      DzCommune(latin: 'Aïn Kebira', arabic: 'عين كبيرة'),
      DzCommune(latin: 'Aïn Nehala', arabic: 'عين نهلة'),
      DzCommune(latin: 'Aïn Tellout', arabic: 'عين تلوّت'),
      DzCommune(latin: 'Amieur', arabic: 'عمير'),
      DzCommune(latin: 'Azails', arabic: 'عزايل'),
      DzCommune(latin: 'Beni Bahdel', arabic: 'بني بهدل'),
      DzCommune(latin: 'Beni Khellad', arabic: 'بني خلاّد'),
      DzCommune(latin: 'Beni Ouarsous', arabic: 'بني وارسوس'),
      DzCommune(latin: 'Beni Smiel', arabic: 'بني سميّل'),
      DzCommune(latin: 'Bouderbala', arabic: 'بودربالة'),
      DzCommune(latin: 'Bouhlou', arabic: 'بوحلو'),
      DzCommune(latin: 'Chorfa', arabic: 'الشرفة'),
      DzCommune(latin: 'Dar Yaghmouracene', arabic: 'دار يغمراسن'),
      DzCommune(latin: 'Djebala', arabic: 'جبالة'),
      DzCommune(latin: 'El Aricha', arabic: 'العريشة'),
      DzCommune(latin: 'El Fehoul', arabic: 'الفحول'),
      DzCommune(latin: 'El Hassi', arabic: 'الحاسي'),
      DzCommune(latin: 'El Houassi', arabic: 'الحواسي'),
      DzCommune(latin: 'El Kerma', arabic: 'الكرمة'),
      DzCommune(
        latin: 'El Ouled',
        arabic: 'الأولاد',
      ), // TODO(AR): nom exact locale
      DzCommune(latin: 'Msirda Fouaga', arabic: 'مسيردة الفواقة'),
      DzCommune(latin: 'Oued Lakhdar', arabic: 'وادي الأخضر'),
      DzCommune(latin: 'Ras El Ma', arabic: 'رأس الماء'),
      DzCommune(latin: 'Sidi Ali Benyoub', arabic: 'سيدي علي بن يوب'),
      DzCommune(latin: 'Tlemcen (rurale)', arabic: 'تلمسان (ريفية)'),
      DzCommune(latin: 'Zariffet', arabic: 'زريفات'),
    ],
  ),

  // 14 — Tiaret
  DzWilaya(
    code: '14',
    latinName: 'Tiaret',
    arabicName: 'تيارت',
    communes: [
      DzCommune(latin: 'Tiaret', arabic: 'تيارت'),
      DzCommune(latin: 'Aïn Bouchekif', arabic: 'عين بوشكف'),
      DzCommune(latin: 'Aïn Deheb', arabic: 'عين الذهب'),
      DzCommune(latin: 'Aïn Kermes', arabic: 'عين كرمس'),
      DzCommune(latin: 'Aïn Zada', arabic: 'عين زادة'),
      DzCommune(latin: 'Dahmouni', arabic: 'دحموني'),
      DzCommune(latin: 'Djillali Ben Amar', arabic: 'جلالي بن عمار'),
      DzCommune(latin: 'Frenda', arabic: 'فرندة'),
      DzCommune(latin: 'Guertoufa', arabic: 'ڤرتوفة'),
      DzCommune(latin: 'Hamadia', arabic: 'حمادية'),
      DzCommune(latin: 'Ksar Chellala', arabic: 'قصر الشلالة'),
      DzCommune(latin: 'Madna', arabic: 'مادنة'),
      DzCommune(latin: 'Mahdia', arabic: 'مهدية'),
      DzCommune(latin: 'Medroussa', arabic: 'مدروسة'),
      DzCommune(latin: 'Medrissa', arabic: 'مدريسة'),
      DzCommune(latin: 'Mellakou', arabic: 'ملاكو'),
      DzCommune(latin: 'Meghila', arabic: 'مغيلة'),
      DzCommune(latin: 'Nadorah', arabic: 'ناظورة'),
      DzCommune(latin: 'Oued Lili', arabic: 'وادي ليلي'),
      DzCommune(latin: 'Rahouia', arabic: 'رحوية'),
      DzCommune(latin: 'Sebaine', arabic: 'السبعين'),
      DzCommune(latin: 'Sebt', arabic: 'السبت'),
      DzCommune(latin: 'Serghine', arabic: 'سرغين'),
      DzCommune(latin: 'Sidi Abderrahmane', arabic: 'سيدي عبد الرحمن'),
      DzCommune(latin: 'Sidi Ali Mellal', arabic: 'سيدي علي ملال'),
      DzCommune(latin: 'Sidi Bakhti', arabic: 'سيدي بختي'),
      DzCommune(latin: 'Sidi Hosni', arabic: 'سيدي حسني'),
      DzCommune(latin: 'Sougueur', arabic: 'السوقر'),
      DzCommune(latin: 'Tagdemt', arabic: 'تاقدمت'),
      DzCommune(latin: 'Takhemaret', arabic: 'تاخمارت'),
      DzCommune(latin: 'Tidda', arabic: 'تيدة'),
      DzCommune(latin: 'Tousnina', arabic: 'توسنينة'),
      DzCommune(
        latin: 'Zmalet El Emir Abdelkader',
        arabic: 'زمالة الأمير عبد القادر',
      ),
    ],
  ),

  // 15 — Tizi Ouzou
  DzWilaya(
    code: '15',
    latinName: 'Tizi Ouzou',
    arabicName: 'تيزي وزو',
    communes: [
      DzCommune(latin: 'Tizi Ouzou', arabic: 'تيزي وزو'),
      DzCommune(latin: 'Aghribs', arabic: 'أغريب'),
      DzCommune(latin: 'Aïn El Hammam', arabic: 'عين الحمام'),
      DzCommune(latin: 'Aït Aggouacha', arabic: 'آيت عقواشة'),
      DzCommune(latin: 'Aït Bouaddou', arabic: 'آيت بوعدو'),
      DzCommune(latin: 'Aït Boumehdi', arabic: 'آيت بومهدي'),
      DzCommune(latin: 'Aït Chafaa', arabic: 'آيت شافع'),
      DzCommune(latin: 'Aït Khellili', arabic: 'آيت خليلي'),
      DzCommune(latin: 'Aït Mahmoud', arabic: 'آيت محمود'),
      DzCommune(latin: 'Aït Oumalou', arabic: 'آيت أومالو'),
      DzCommune(latin: 'Aït Toudert', arabic: 'آيت تودرت'),
      DzCommune(latin: 'Aït Yahia', arabic: 'آيت يحيى'),
      DzCommune(latin: 'Aït Yahia Moussa', arabic: 'آيت يحيى موسى'),
      DzCommune(latin: 'Aït Yenni', arabic: 'آيت يني'),
      DzCommune(latin: 'Akbil', arabic: 'أقبيل'),
      DzCommune(latin: 'Akerrou', arabic: 'أقرو'),
      DzCommune(latin: 'Azazga', arabic: 'عزازقة'),
      DzCommune(latin: 'Azeffoun', arabic: 'أزفون'),
      DzCommune(latin: 'Beni Aïssi', arabic: 'بني عيسى'),
      DzCommune(latin: 'Beni Douala', arabic: 'بني دوالة'),
      DzCommune(latin: 'Beni Yenni', arabic: 'بني يني'),
      DzCommune(latin: 'Boghni', arabic: 'بوغني'),
      DzCommune(latin: 'Boudjima', arabic: 'بودجيمة'),
      DzCommune(latin: 'Bounouh', arabic: 'بونوح'),
      DzCommune(latin: 'Draa Ben Khedda', arabic: 'ذراع بن خدة'),
      DzCommune(latin: 'Draa El Mizan', arabic: 'ذراع الميزان'),
      DzCommune(latin: 'Freha', arabic: 'فريحة'),
      DzCommune(latin: 'Frikat', arabic: 'فريقات'),
      DzCommune(latin: 'Iflissen', arabic: 'إفليسن'),
      DzCommune(latin: 'Illilten', arabic: 'إيللتن'),
      DzCommune(latin: 'Illoula Oumalou', arabic: 'إيلولة أومالو'),
      DzCommune(latin: 'Imsouhal', arabic: 'إمسوحال'),
      DzCommune(latin: 'Irdjen', arabic: 'إيرجن'),
      DzCommune(latin: 'Larbaa Nath Irathen', arabic: 'الأربعاء ناث إيراثن'),
      DzCommune(latin: 'Makouda', arabic: 'ماكودة'),
      DzCommune(latin: 'Mekla', arabic: 'مقلا'),
      DzCommune(latin: 'Mizrana', arabic: 'مزرانة'),
      DzCommune(latin: 'Ouacif', arabic: 'واقسيف'),
      DzCommune(latin: 'Ouadhia', arabic: 'واضية'),
      DzCommune(latin: 'Souamaa', arabic: 'سوامع'),
      DzCommune(latin: 'Souk El Tenine', arabic: 'سوق الاثنين'),
      DzCommune(latin: 'Tadmaït', arabic: 'تادمايت'),
      DzCommune(latin: 'Tigzirt', arabic: 'تيقزيرت'),
      DzCommune(latin: 'Tirmitine', arabic: 'تيرمتين'),
      DzCommune(latin: 'Tizi Ghenif', arabic: 'تيزي غنيف'),
      DzCommune(latin: 'Tizi N\'Berber', arabic: 'تيزي نبربر'),
      DzCommune(latin: 'Tizi Rached', arabic: 'تيزي راشد'),
      DzCommune(latin: 'Yakouren', arabic: 'ياكورَن'),
      DzCommune(latin: 'Yatafene', arabic: 'ياتافن'),
      DzCommune(latin: 'Zekri', arabic: 'زكري'),
      DzCommune(
        latin: 'Iferhounene',
        arabic: 'إفrehounene',
      ), // TODO(AR) harmoniser
      DzCommune(latin: 'Aït Boumahdi', arabic: 'آيت بومهدي'),
    ],
  ),
];

const List<DzWilaya> dzWilayasPart4 = [
  // 16 — Alger
  DzWilaya(
    code: '16',
    latinName: 'Alger',
    arabicName: 'الجزائر',
    communes: [
      DzCommune(latin: 'Alger Centre', arabic: 'الجزائر الوسطى'),
      DzCommune(latin: 'Sidi M’Hamed', arabic: 'سيدي أمحمد'),
      DzCommune(latin: 'El Madania', arabic: 'المدنية'),
      DzCommune(latin: 'Belouizdad', arabic: 'بلوزداد'),
      DzCommune(latin: 'Bab El Oued', arabic: 'باب الوادي'),
      DzCommune(latin: 'Bologhine', arabic: 'بولوغين'),
      DzCommune(latin: 'Casbah', arabic: 'القصبة'),
      DzCommune(latin: 'Oued Koriche', arabic: 'وادي قريش'),
      DzCommune(latin: 'Bir Mourad Rais', arabic: 'بئر مراد رايس'),
      DzCommune(latin: 'El Biar', arabic: 'الابيار'),
      DzCommune(latin: 'Bouzareah', arabic: 'بوزريعة'),
      DzCommune(latin: 'Birkhadem', arabic: 'بئر خادم'),
      DzCommune(latin: 'El Harrach', arabic: 'الحراش'),
      DzCommune(latin: 'Oued Smar', arabic: 'وادي السمار'),
      DzCommune(latin: 'Bourouba', arabic: 'بوروبة'),
      DzCommune(latin: 'Hussein Dey', arabic: 'حسين داي'),
      DzCommune(latin: 'Kouba', arabic: 'القبة'),
      DzCommune(latin: 'Bachedjerah', arabic: 'باش جراح'),
      DzCommune(latin: 'Dar El Beïda', arabic: 'الدار البيضاء'),
      DzCommune(latin: 'Bab Ezzouar', arabic: 'باب الزوار'),
      DzCommune(latin: 'Ben Aknoun', arabic: 'بن عكنون'),
      DzCommune(latin: 'Dely Ibrahim', arabic: 'دالي إبراهيم'),
      DzCommune(latin: 'El Hammamet', arabic: 'الحمامات'),
      DzCommune(latin: 'Raïs Hamidou', arabic: 'الرايس حميدو'),
      DzCommune(latin: 'Djasr Kasentina', arabic: 'جسر قسنطينة'),
      DzCommune(latin: 'El Mouradia', arabic: 'المرادية'),
      DzCommune(latin: 'Hydra', arabic: 'حيدرة'),
      DzCommune(latin: 'Mohammadia', arabic: 'المحمدية'),
      DzCommune(latin: 'Bordj El Kiffan', arabic: 'برج الكيفان'),
      DzCommune(latin: 'El Magharia', arabic: 'المغارية'),
      DzCommune(latin: 'Beni Messous', arabic: 'بني مسوس'),
      DzCommune(latin: 'Les Eucalyptus', arabic: 'الكاليتوس'),
      DzCommune(latin: 'Baba Hassen', arabic: 'بابا حسن'),
      DzCommune(latin: 'Douera', arabic: 'الدويرة'),
      DzCommune(latin: 'Draria', arabic: 'الدرارية'),
      DzCommune(latin: 'El Achour', arabic: 'العاشور'),
      DzCommune(latin: 'Ouled Fayet', arabic: 'أولاد فايت'),
      DzCommune(latin: 'Cheraga', arabic: 'الشراڤة'),
      DzCommune(latin: 'Staoueli', arabic: 'سطاوالي'),
      DzCommune(latin: 'Zeralda', arabic: 'زرالدة'),
      DzCommune(latin: 'Maalma', arabic: 'المعالمة'),
      DzCommune(latin: 'Rahmania', arabic: 'الرحمانية'),
      DzCommune(latin: 'Souidania', arabic: 'سويدانية'),
      DzCommune(latin: 'Khraicia', arabic: 'الخرايسية'),
      DzCommune(latin: 'Aïn Benian', arabic: 'عين بنيان'),
    ],
  ),

  // 17 — Djelfa
  DzWilaya(
    code: '17',
    latinName: 'Djelfa',
    arabicName: 'الجلفة',
    communes: [
      DzCommune(latin: 'Djelfa', arabic: 'الجلفة'),
      DzCommune(latin: 'Aïn Chouhada', arabic: 'عين الشهداء'),
      DzCommune(latin: 'Aïn El Ibel', arabic: 'عين الإبل'),
      DzCommune(latin: 'Aïn Feka', arabic: 'عين فكا'),
      DzCommune(latin: 'Aïn Maabed', arabic: 'عين معبد'),
      DzCommune(latin: 'Amourah', arabic: 'عمورة'),
      DzCommune(latin: 'Benhar', arabic: 'بن هار'),
      DzCommune(latin: 'Benyagoub', arabic: 'بن يعقوب'),
      DzCommune(latin: 'Birine', arabic: 'بيرين'),
      DzCommune(latin: 'Bouira Lahdeb', arabic: 'بويرة الأحداب'),
      DzCommune(latin: 'Charef', arabic: 'الشرف'),
      DzCommune(latin: 'Dar Chioukh', arabic: 'دار الشيوخ'),
      DzCommune(latin: 'Deldoul', arabic: 'دلدول'),
      DzCommune(latin: 'Douis', arabic: 'دويس'),
      DzCommune(latin: 'El Guedid', arabic: 'القديد'),
      DzCommune(latin: 'El Idrissia', arabic: 'الإدريسية'),
      DzCommune(latin: 'El Khemis', arabic: 'الخميس'),
      DzCommune(latin: 'Faidh El Botma', arabic: 'فيض البطمة'),
      DzCommune(latin: 'Guernini', arabic: 'ڤرنيني'),
      DzCommune(latin: 'Guettara', arabic: 'قطارة'),
      DzCommune(latin: 'Had Sahary', arabic: 'حد الصحاري'),
      DzCommune(latin: 'Hassi Bahbah', arabic: 'حاسي بحبح'),
      DzCommune(latin: 'Hassi El Euch', arabic: 'حاسي العش'),
      DzCommune(latin: 'Hassi Fedoul', arabic: 'حاسي فدول'),
      DzCommune(latin: 'Messaad', arabic: 'مسعد'),
      DzCommune(latin: 'Moudjebara', arabic: 'مجبارة'),
      DzCommune(latin: 'Oum Laadham', arabic: 'أم لعظام'),
      DzCommune(latin: 'Sed Rahal', arabic: 'سد الرحال'),
      DzCommune(latin: 'Selmana', arabic: 'سلمانة'),
      DzCommune(latin: 'Sidi Baizid', arabic: 'سيدي بايزيد'),
      DzCommune(latin: 'Sidi Ladjel', arabic: 'سيدي لعجال'),
      DzCommune(latin: 'Zaccar', arabic: 'زكار'),
      DzCommune(latin: 'Zaafrane', arabic: 'زعفران'),
    ],
  ),

  // 18 — Jijel
  DzWilaya(
    code: '18',
    latinName: 'Jijel',
    arabicName: 'جيجل',
    communes: [
      DzCommune(latin: 'Jijel', arabic: 'جيجل'),
      DzCommune(latin: 'El Milia', arabic: 'الميلية'),
      DzCommune(latin: 'Taher', arabic: 'الطاهير'),
      DzCommune(latin: 'Chekfa', arabic: 'الشقفة'),
      DzCommune(latin: 'Chahna', arabic: 'الشنا'),
      DzCommune(latin: 'El Aouana', arabic: 'العوانة'),
      DzCommune(latin: 'El Ancer', arabic: 'العنصر'),
      DzCommune(latin: 'El Kennar Nouchfi', arabic: 'القنار نشفي'),
      DzCommune(latin: 'Texenna', arabic: 'تاكسنة'),
      DzCommune(latin: 'Oudjana', arabic: 'أودكان/أوجانة'),
      DzCommune(latin: 'Kaous', arabic: 'قاوس'),
      DzCommune(latin: 'Ghebala', arabic: 'غبالة'),
      DzCommune(
        latin: 'Bouraoui Belhadef',
        arabic: 'بورواوBelhadef/بوراوي بلهادف',
      ),
      DzCommune(latin: 'Selma Benziada', arabic: 'سلمى بن زيادة'),
      DzCommune(latin: 'Sidi Abdelaziz', arabic: 'سيدي عبد العزيز'),
      DzCommune(latin: 'Djimla', arabic: 'جيملة'),
      DzCommune(latin: 'Ziama Mansouriah', arabic: 'زيامة منصورية'),
      DzCommune(latin: 'Bordj T\'har', arabic: 'برج الطهر'),
      DzCommune(latin: 'Erraguene Souissi', arabic: 'إيراقن سويسي'),
      DzCommune(latin: 'Kheiri Oued Adjoul', arabic: 'خيـري وادي عجول'),
      DzCommune(latin: 'Settara', arabic: 'ستارة'),
      DzCommune(latin: 'El Ghedir', arabic: 'الغدير'),
      DzCommune(latin: 'Beni Ahmed', arabic: 'بني أحمد'),
      DzCommune(latin: 'Beni Yadjis', arabic: 'بني ياجيس'),
      DzCommune(latin: 'Sidi Marouf', arabic: 'سيدي معروف'),
      DzCommune(latin: 'Bousselam', arabic: 'بوسلام'),
      DzCommune(latin: 'Hammadi Krouma', arabic: 'حمادي كرومة'),
      DzCommune(latin: 'Emjez Edchich', arabic: 'مجّـاز الدشيش'),
      DzCommune(latin: 'Filfila', arabic: 'فلفلة'),
      DzCommune(latin: 'Aïn El Kebira', arabic: 'عين الكبيرة'),
    ],
  ),

  // 19 — Sétif
  DzWilaya(
    code: '19',
    latinName: 'Sétif',
    arabicName: 'سطيف',
    communes: [
      DzCommune(latin: 'Sétif', arabic: 'سطيف'),
      DzCommune(latin: 'Aïn Abessa', arabic: 'عين عباسة'),
      DzCommune(latin: 'Aïn Arnat', arabic: 'عين أرنات'),
      DzCommune(latin: 'Aïn Azel', arabic: 'عين أزال'),
      DzCommune(latin: 'Aïn El Kebira', arabic: 'عين الكبيرة'),
      DzCommune(latin: 'Aïn Lahdjar', arabic: 'عين الحجر'),
      DzCommune(latin: 'Aïn Oulmene', arabic: 'عين ولمان'),
      DzCommune(latin: 'Aïn Roua', arabic: 'عين الروى'),
      DzCommune(latin: 'Aïn Sebt', arabic: 'عين السبت'),
      DzCommune(latin: 'Amoucha', arabic: 'عموشة'),
      DzCommune(latin: 'Babor', arabic: 'بابور'),
      DzCommune(latin: 'Bazer Sakhra', arabic: 'بازر سكرة'),
      DzCommune(latin: 'Belaa', arabic: 'بلعة'),
      DzCommune(latin: 'Beni Aziz', arabic: 'بني عزيز'),
      DzCommune(latin: 'Beni Chebana', arabic: 'بني شعبانة'),
      DzCommune(latin: 'Beni Fouda', arabic: 'بني فودة'),
      DzCommune(latin: 'Beni Hocine', arabic: 'بني حسين'),
      DzCommune(latin: 'Beni Mouhli', arabic: 'بني موحلي'),
      DzCommune(latin: 'Beni Oussine', arabic: 'بني وسين'),
      DzCommune(latin: 'Bir El Arch', arabic: 'بئر العرش'),
      DzCommune(latin: 'Bir Haddada', arabic: 'بئر حدادة'),
      DzCommune(latin: 'Bouandas', arabic: 'بوعنداس'),
      DzCommune(latin: 'Bougaa', arabic: 'بوقاعة'),
      DzCommune(latin: 'Boutaleb', arabic: 'بوطالب'),
      DzCommune(latin: 'Dehamcha', arabic: 'دهمشة'),
      DzCommune(latin: 'Djemila', arabic: 'جميلة'),
      DzCommune(latin: 'El Eulma', arabic: 'العلمة'),
      DzCommune(latin: 'El Ouricia', arabic: 'الأوريسيا'),
      DzCommune(latin: 'Guelta Zerka', arabic: 'قلتة زرقاء'),
      DzCommune(latin: 'Guellal', arabic: 'قلال'),
      DzCommune(latin: 'Guenzet', arabic: 'قنزات'),
      DzCommune(latin: 'Guidjel', arabic: 'قجال'),
      DzCommune(latin: 'Hamma', arabic: 'الحامة'),
      DzCommune(latin: 'Hammam Guergour', arabic: 'حمام قرقور'),
      DzCommune(latin: 'Harbil', arabic: 'حربيل'),
      DzCommune(latin: 'Ksar El Abtal', arabic: 'قصر الأبطال'),
      DzCommune(latin: 'Maaouia', arabic: 'معاوية'),
      DzCommune(latin: 'Mezloug', arabic: 'مزلوق'),
      DzCommune(latin: 'Oued El Barad', arabic: 'وادي البارد'),
      DzCommune(latin: 'Ouled Addouane', arabic: 'أولاد عدوان'),
      DzCommune(latin: 'Ouled Sabor', arabic: 'أولاد صابر'),
      DzCommune(latin: 'Ouled Si Ahmed', arabic: 'أولاد سي أحمد'),
      DzCommune(latin: 'Rosfa', arabic: 'الرصفة'),
      DzCommune(latin: 'Salah Bey', arabic: 'صالح باي'),
      DzCommune(latin: 'Serdj El Ghoul', arabic: 'سردج الغول'),
      DzCommune(latin: 'Tachouda', arabic: 'تاشودة'),
      DzCommune(latin: 'Taya', arabic: 'تاية'),
      DzCommune(latin: 'Tella', arabic: 'تيلا'),
      DzCommune(latin: 'Tizi N’Bechar', arabic: 'تيزي نبشار'),
    ],
  ),

  // 20 — Saïda
  DzWilaya(
    code: '20',
    latinName: 'Saïda',
    arabicName: 'سعيدة',
    communes: [
      DzCommune(latin: 'Saïda', arabic: 'سعيدة'),
      DzCommune(latin: 'Aïn El Hadjar', arabic: 'عين الحجر'),
      DzCommune(latin: 'Aïn Sekhouna', arabic: 'عين سخونة'),
      DzCommune(latin: 'Doui Thabet', arabic: 'ضوي ثابت'),
      DzCommune(latin: 'El Hassasna', arabic: 'الحساسنة'),
      DzCommune(latin: 'Hounet', arabic: 'هونت'),
      DzCommune(latin: 'Maamora', arabic: 'المعمورة'),
      DzCommune(latin: 'Moulay Larbi', arabic: 'مولاي العربي'),
      DzCommune(latin: 'Ouled Brahim', arabic: 'أولاد إبراهيم'),
      DzCommune(latin: 'Ouled Khaled', arabic: 'أولاد خالد'),
      DzCommune(latin: 'Sidi Ahmed', arabic: 'سيدي أحمد'),
      DzCommune(latin: 'Sidi Amar', arabic: 'سيدي عمار'),
      DzCommune(latin: 'Sidi Boubekeur', arabic: 'سيدي بوبكر'),
      DzCommune(latin: 'Tircine', arabic: 'ترسين'),
      DzCommune(latin: 'Youb', arabic: 'يوب'),
    ],
  ),
];
// lib/data/dz_admin_ar_part5.dart
// Partie 5/?: 21 Skikda, 22 Sidi Bel Abbès, 23 Annaba, 24 Guelma, 25 Constantine

const List<DzWilaya> dzWilayasPart5 = [
  // 21 — Skikda
  DzWilaya(
    code: '21',
    latinName: 'Skikda',
    arabicName: 'سكيكدة',
    communes: [
      DzCommune(latin: 'Skikda', arabic: 'سكيكدة'),
      DzCommune(latin: 'Aïn Bouziane', arabic: 'عين بوزيان'),
      DzCommune(latin: 'Aïn Charchar', arabic: 'عين شرشار'),
      DzCommune(latin: 'Aïn Kechra', arabic: 'عين قشرة'),
      DzCommune(latin: 'Azzaba', arabic: 'عزابة'),
      DzCommune(latin: 'Ben Azzouz', arabic: 'بن عزوز'),
      DzCommune(latin: 'Beni Bechir', arabic: 'بني بشير'),
      DzCommune(latin: 'Beni Oulbane', arabic: 'بني ولبان'),
      DzCommune(latin: 'Bekkouche Lakhdar', arabic: 'بكوش لخضر'),
      DzCommune(latin: 'Bouchetata', arabic: 'بوشطاطة'),
      DzCommune(latin: 'Cheraia', arabic: 'الشرايع'),
      DzCommune(latin: 'Collo', arabic: 'القل'),
      DzCommune(latin: 'Djendel Saadi Mohamed', arabic: 'جندل السعدي محمد'),
      DzCommune(latin: 'El Ghedir', arabic: 'الغدير'),
      DzCommune(latin: 'El Harrouch', arabic: 'الحروش'),
      DzCommune(latin: 'El Hadaiek', arabic: 'الحدائق'),
      DzCommune(latin: 'El Marsa', arabic: 'المرسى'),
      DzCommune(latin: 'Emjez Edchich', arabic: 'مجاز الدشيش'),
      DzCommune(latin: 'Es Sebt', arabic: 'السبت'),
      DzCommune(latin: 'Filfila', arabic: 'فلفلة'),
      DzCommune(latin: 'Hammadi Krouma', arabic: 'حمادي كرومة'),
      DzCommune(latin: 'Kanoua', arabic: 'قنوة'),
      DzCommune(latin: 'Kerkera', arabic: 'الكركرة'),
      DzCommune(latin: 'Oued Zhour', arabic: 'وادي الزهور'),
      DzCommune(latin: 'Oum Toub', arabic: 'أم الطوب'),
      DzCommune(latin: 'Ramdane Djamel', arabic: 'رمضان جمال'),
      DzCommune(latin: 'Salah Bouchaour', arabic: 'صالح بوشعور'),
      DzCommune(latin: 'Tamalous', arabic: 'تمالوس'),
      DzCommune(latin: 'Zerdazas', arabic: 'زرادزة'),
      DzCommune(latin: 'Zitouna', arabic: 'الزيتونة'),
    ],
  ),

  // 22 — Sidi Bel Abbès
  DzWilaya(
    code: '22',
    latinName: 'Sidi Bel Abbès',
    arabicName: 'سيدي بلعباس',
    communes: [
      DzCommune(latin: 'Sidi Bel Abbès', arabic: 'سيدي بلعباس'),
      DzCommune(latin: 'Aïn Adden', arabic: 'عين عدان'),
      DzCommune(latin: 'Aïn El Berd', arabic: 'عين البرد'),
      DzCommune(latin: 'Aïn Kada', arabic: 'عين قادة'),
      DzCommune(latin: 'Aïn Tindamine', arabic: 'عين تندمين'),
      DzCommune(latin: 'Amarnas', arabic: 'عمارنة'),
      DzCommune(latin: 'Belarbi', arabic: 'بلعربي'),
      DzCommune(latin: 'Ben Badis', arabic: 'بن باديس'),
      DzCommune(latin: 'Benachiba Chelia', arabic: 'بن عشيبة شلية'),
      DzCommune(latin: 'Beni Ameur', arabic: 'بني عامر'),
      DzCommune(latin: 'Boudjebaa El Bordj', arabic: 'بودجيبة البرج'),
      DzCommune(latin: 'Boukhana', arabic: 'بوخانة'),
      DzCommune(latin: 'Chetouane Belaila', arabic: 'شتوان بليلة'),
      DzCommune(latin: 'Dhaya', arabic: 'الضاية'),
      DzCommune(latin: 'El Haçaiba', arabic: 'الحصيبة'),
      DzCommune(latin: 'Hassi Dahou', arabic: 'حاسي دحو'),
      DzCommune(latin: 'Hassi Zahana', arabic: 'حاسي زهانة'),
      DzCommune(latin: 'Lamtar', arabic: 'لمطار'),
      DzCommune(latin: 'Makedra', arabic: 'مكدرة'),
      DzCommune(latin: 'Marhoum', arabic: 'مرقوم'),
      DzCommune(latin: 'Merine', arabic: 'مرين'),
      DzCommune(latin: 'Mostefa Ben Brahim', arabic: 'مصطفى بن ابراهيم'),
      DzCommune(latin: 'Moulay Slissen', arabic: 'مولاي سليسن'),
      DzCommune(latin: 'Oued Sebaa', arabic: 'وادي السبع'),
      DzCommune(latin: 'Oued Sefioun', arabic: 'وادي سفيون'),
      DzCommune(latin: 'Ras El Ma', arabic: 'رأس الماء'),
      DzCommune(latin: 'Redjem Demouche', arabic: 'رجم دموش'),
      DzCommune(latin: 'Sidi Ali Benyoub', arabic: 'سيدي علي بن يوب'),
      DzCommune(latin: 'Sidi Brahim', arabic: 'سيدي ابراهيم'),
      DzCommune(latin: 'Sidi Chaib', arabic: 'سيدي شعيب'),
      DzCommune(latin: 'Sidi Dahou', arabic: 'سيدي دحو'),
      DzCommune(latin: 'Sidi Hamadouche', arabic: 'سيدي حمادوش'),
      DzCommune(latin: 'Sidi Khaled', arabic: 'سيدي خالد'),
      DzCommune(latin: 'Sidi Lahcene', arabic: 'سيدي لحسن'),
      DzCommune(latin: 'Sidi Yacoub', arabic: 'سيدي يعقوب'),
      DzCommune(latin: 'Tabia', arabic: 'طابية'),
      DzCommune(latin: 'Tenira', arabic: 'تنيرة'),
      DzCommune(latin: 'Tessala', arabic: 'تسالة'),
      DzCommune(latin: 'Teghalimet', arabic: 'تغاليمت'),
      DzCommune(latin: 'Tilmouni', arabic: 'تلموني'),
      DzCommune(latin: 'Zerouala', arabic: 'زروالة'),
    ],
  ),

  // 23 — Annaba
  DzWilaya(
    code: '23',
    latinName: 'Annaba',
    arabicName: 'عنابة',
    communes: [
      DzCommune(latin: 'Annaba', arabic: 'عنابة'),
      DzCommune(latin: 'Aïn Berda', arabic: 'عين الباردة'),
      DzCommune(latin: 'Berrahal', arabic: 'برحال'),
      DzCommune(latin: 'Cheurfa', arabic: 'الشرفة'),
      DzCommune(
        latin: 'Chetaïbi',
        arabic: 'شاطئ بونـو/شطايبي',
      ), // شطايبي هو الأكثر شيوعًا
      DzCommune(latin: 'El Bouni', arabic: 'البوني'),
      DzCommune(latin: 'El Hadjar', arabic: 'الحجار'),
      DzCommune(latin: 'Eulma', arabic: 'العلمة'),
      DzCommune(latin: 'Oued El Aneb', arabic: 'وادي العنب'),
      DzCommune(latin: 'Seraïdi', arabic: 'سرايدي'),
      DzCommune(latin: 'Sidi Amar', arabic: 'سيدي عمار'),
    ],
  ),

  // 24 — Guelma
  DzWilaya(
    code: '24',
    latinName: 'Guelma',
    arabicName: 'قالمة',
    communes: [
      DzCommune(latin: 'Guelma', arabic: 'قالمة'),
      DzCommune(latin: 'Aïn Ben Beida', arabic: 'عين بن بيضاء'),
      DzCommune(latin: 'Aïn Larbi', arabic: 'عين العربي'),
      DzCommune(latin: 'Aïn Makhlouf', arabic: 'عين مخلوف'),
      DzCommune(latin: 'Aïn Reggada', arabic: 'عين رقادة'),
      DzCommune(latin: 'Belkheir', arabic: 'بلخير'),
      DzCommune(latin: 'Ben Djarah', arabic: 'بن جراح'),
      DzCommune(latin: 'Beni Mezline', arabic: 'بني مزلين'),
      DzCommune(latin: 'Bou Hamdane', arabic: 'بوحمدان'),
      DzCommune(latin: 'Bouati Mahmoud', arabic: 'بوعاتي محمود'),
      DzCommune(latin: 'Bou Hachana', arabic: 'بوحشانة'),
      DzCommune(latin: 'Bouchegouf', arabic: 'بوشقوف'),
      DzCommune(latin: 'Dahouara', arabic: 'داهوارة'),
      DzCommune(latin: 'Djeballah Khemissi', arabic: 'جبالة الخميسي'),
      DzCommune(latin: 'El Fedjoudj', arabic: 'الفجوج'),
      DzCommune(
        latin: 'El Kouahi',
        arabic: 'الكواهي',
      ), // parfois absent, dépend des versions
      DzCommune(latin: 'El Taref (Guelma)', arabic: 'الطارف (قالمة)'),
      DzCommune(latin: 'Guelaat Bou Sbaa', arabic: 'قلعة بوصبع'),
      DzCommune(latin: 'Hammam Debagh', arabic: 'حمام دباغ'),
      DzCommune(latin: 'Hammam N\'Bails', arabic: 'حمام النبائل'),
      DzCommune(latin: 'Heliopolis', arabic: 'هيليوبوليس'),
      DzCommune(latin: 'Houari Boumédienne', arabic: 'هواري بومدين'),
      DzCommune(latin: 'Khezaras', arabic: 'خزارة'),
      DzCommune(latin: 'Medjez Sfa', arabic: 'مجاز صفا'),
      DzCommune(latin: 'Nechmaya', arabic: 'نشماية'),
      DzCommune(latin: 'Oued Cheham', arabic: 'وادي الشحم'),
      DzCommune(latin: 'Oued Fragha', arabic: 'وادي فراغة'),
      DzCommune(latin: 'Ras El Agba', arabic: 'رأس العقبة'),
      DzCommune(latin: 'Roknia', arabic: 'رقنية'),
      DzCommune(latin: 'Sellaoua Announa', arabic: 'سلاوة عنونة'),
      DzCommune(latin: 'Tamlouka', arabic: 'تاملوكة'),
    ],
  ),

  // 25 — Constantine
  DzWilaya(
    code: '25',
    latinName: 'Constantine',
    arabicName: 'قسنطينة',
    communes: [
      DzCommune(latin: 'Constantine', arabic: 'قسنطينة'),
      DzCommune(latin: 'Aïn Abid', arabic: 'عين عبيد'),
      DzCommune(latin: 'Aïn Smara', arabic: 'عين سمارة'),
      DzCommune(latin: 'Ben Badis', arabic: 'بن باديس'),
      DzCommune(latin: 'Beni Hamidene', arabic: 'بني حميدان'),
      DzCommune(latin: 'Didouche Mourad', arabic: 'ديدوش مراد'),
      DzCommune(latin: 'El Khroub', arabic: 'الخروب'),
      DzCommune(latin: 'Hamma Bouziane', arabic: 'حامة بوزيان'),
      DzCommune(latin: 'Ibn Ziad', arabic: 'ابن زياد'),
      DzCommune(
        latin: 'Mesentour',
        arabic: 'مسنتور',
      ), // parfois écrit مسعود بوقاطع؟ selon sources
      DzCommune(latin: 'Ouled Rahmoun', arabic: 'أولاد رحمون'),
      DzCommune(latin: 'Zighoud Youcef', arabic: 'زيغود يوسف'),
    ],
  ),
];
// lib/data/dz_admin_ar_part6.dart
// Partie 6/?: 26 Médéa, 27 Mostaganem, 28 M’Sila, 29 Mascara, 30 Ouargla

const List<DzWilaya> dzWilayasPart6 = [
  // 26 — Médéa
  DzWilaya(
    code: '26',
    latinName: 'Médéa',
    arabicName: 'المدية',
    communes: [
      DzCommune(latin: 'Médéa', arabic: 'المدية'),
      DzCommune(latin: 'Aïn Boucif', arabic: 'عين بوسيف'),
      DzCommune(latin: 'Aïn Ouksir', arabic: 'عين اقصير'),
      DzCommune(latin: 'Aïn Dheb', arabic: 'عين الدهب'),
      DzCommune(latin: 'Aziz', arabic: 'عزيز'),
      DzCommune(latin: 'Baâta', arabic: 'بعطة'),
      DzCommune(latin: 'Benchicao', arabic: 'بن شكاو'),
      DzCommune(latin: 'Beni Slimane', arabic: 'بني سليمان'),
      DzCommune(latin: 'Berrouaghia', arabic: 'البرواقية'),
      DzCommune(latin: 'Bir Ben Laabed', arabic: 'بئر بن عابد'),
      DzCommune(latin: 'Bouaich', arabic: 'بوعيش'),
      DzCommune(latin: 'Bouchrahil', arabic: 'بوشراحيل'),
      DzCommune(latin: 'Chahbounia', arabic: 'شهبونية'),
      DzCommune(latin: 'Chelalet El Adhaoura', arabic: 'شلالة العذاورة'),
      DzCommune(latin: 'Derrag', arabic: 'دراق'),
      DzCommune(latin: 'Djouab', arabic: 'جواع'),
      DzCommune(latin: 'El Azizia', arabic: 'العزيزية'),
      DzCommune(latin: 'El Guelbelkebir', arabic: 'القلب الكبير'),
      DzCommune(latin: 'El Omaria', arabic: 'العمارية'),
      DzCommune(latin: 'Hannacha', arabic: 'حناشة'),
      DzCommune(latin: 'Kef Lakhdar', arabic: 'الكاف الأخضر'),
      DzCommune(latin: 'Ksar El Boukhari', arabic: 'قصر البخاري'),
      DzCommune(latin: 'Mezerana', arabic: 'مزيرعة'),
      DzCommune(latin: 'Mihoub', arabic: 'ميهوب'),
      DzCommune(latin: 'Ouamri', arabic: 'وعمري'),
      DzCommune(latin: 'Ouled Bouachra', arabic: 'أولاد بوعشرة'),
      DzCommune(latin: 'Ouled Deid', arabic: 'أولاد دايد'),
      DzCommune(latin: 'Ouled Hellal', arabic: 'أولاد هلال'),
      DzCommune(latin: 'Ouled Maaref', arabic: 'أولاد معارف'),
      DzCommune(latin: 'Ouled Sidi Brahim', arabic: 'أولاد سيدي ابراهيم'),
      DzCommune(latin: 'Oued Harbil', arabic: 'وادي حربيل'),
      DzCommune(latin: 'Ouzera', arabic: 'وزرة'),
      DzCommune(latin: 'Rebaïa', arabic: 'الرّباعية'),
      DzCommune(latin: 'Sedraya', arabic: 'سدراية'),
      DzCommune(latin: 'Seghouane', arabic: 'السغوان'),
      DzCommune(latin: 'Sidi Damed', arabic: 'سيدي دامد'),
      DzCommune(latin: 'Sidi Naamane', arabic: 'سيدي نعمان'),
      DzCommune(latin: 'Souagui', arabic: 'السواقي'),
      DzCommune(latin: 'Tablat', arabic: 'تابلاط'),
      DzCommune(latin: 'Tamesguida', arabic: 'تامسقيدة'),
      DzCommune(latin: 'Tizi Mahdi', arabic: 'تيزي مهدي'),
    ],
  ),

  // 27 — Mostaganem
  DzWilaya(
    code: '27',
    latinName: 'Mostaganem',
    arabicName: 'مستغانم',
    communes: [
      DzCommune(latin: 'Mostaganem', arabic: 'مستغانم'),
      DzCommune(latin: 'Achaacha', arabic: 'عشعاشة'),
      DzCommune(latin: 'Aïn Boudinar', arabic: 'عين بودينار'),
      DzCommune(latin: 'Aïn Sidi Cherif', arabic: 'عين سيدي الشريف'),
      DzCommune(latin: 'Benabdelmalek Ramdane', arabic: 'بن عبد المالك رمضان'),
      DzCommune(latin: 'Bouguirat', arabic: 'بوقيراط'),
      DzCommune(
        latin: 'Bou Zedjar / Bouzedjar',
        arabic: 'بوزجار',
      ), // selon sources
      DzCommune(latin: 'Fornaka', arabic: 'فرناقة'),
      DzCommune(latin: 'Hadjadj', arabic: 'حجاج'),
      DzCommune(latin: 'Hassi Mameche', arabic: 'حاسي ماماش'),
      DzCommune(latin: 'Khadra', arabic: 'خضراء'),
      DzCommune(latin: 'Kheireddine', arabic: 'خير الدين'),
      DzCommune(latin: 'Mesra', arabic: 'ماسرة'),
      DzCommune(latin: 'Nekmaria', arabic: 'نكمارية'),
      DzCommune(latin: 'Oued El Kheir', arabic: 'وادي الخير'),
      DzCommune(latin: 'Sayada', arabic: 'صيادة'),
      DzCommune(latin: 'Sidi Ali', arabic: 'سيدي علي'),
      DzCommune(latin: 'Sidi Belattar', arabic: 'سيدي بلعطار'),
      DzCommune(latin: 'Sidi Lakhdar', arabic: 'سيدي لخضر'),
      DzCommune(latin: 'Souaflia', arabic: 'السوافلية'),
      DzCommune(latin: 'Tazgait', arabic: 'تزقايت'),
    ],
  ),

  // 28 — M’Sila
  DzWilaya(
    code: '28',
    latinName: 'M’Sila',
    arabicName: 'المسيلة',
    communes: [
      DzCommune(latin: 'M’Sila', arabic: 'المسيلة'),
      DzCommune(latin: 'Aïn El Hadjel', arabic: 'عين الحجل'),
      DzCommune(latin: 'Aïn El Melh', arabic: 'عين الملح'),
      DzCommune(latin: 'Aïn Errich', arabic: 'عين الريش'),
      DzCommune(latin: 'Belaiba', arabic: 'بلعيبة'),
      DzCommune(latin: 'Ben Srour', arabic: 'بن سرور'),
      DzCommune(latin: 'Berhoum', arabic: 'برهوم'),
      DzCommune(
        latin: 'Bouti Sayeh / Bouti Sayah',
        arabic: 'بوطي سياح',
      ), // selon versions
      DzCommune(latin: 'Bou Saada', arabic: 'بوسعادة'),
      DzCommune(latin: 'Chellal', arabic: 'شلال'),
      DzCommune(latin: 'Dehahna', arabic: 'دهاهنة'),
      DzCommune(latin: 'Djebel Messaad', arabic: 'جبل مسعد'),
      DzCommune(latin: 'Hammam Dhalaa', arabic: 'حمام الضلعة'),
      DzCommune(latin: 'Khettouti Sed El Djir', arabic: 'ختوطي سد الجير'),
      DzCommune(latin: 'Maadid', arabic: 'المعاضيد'),
      DzCommune(latin: 'Maarif', arabic: 'معاريف'),
      DzCommune(latin: 'M’Cif', arabic: 'مسيف'),
      DzCommune(latin: 'Ouanougha', arabic: 'ونزة؟/أونوغة'), // variantes
      DzCommune(latin: 'Ouled Addi Guebala', arabic: 'أولاد عدي قبالة'),
      DzCommune(latin: 'Ouled Derradj', arabic: 'أولاد دراج'),
      DzCommune(latin: 'Ouled Madhi', arabic: 'أولاد ماضي'),
      DzCommune(latin: 'Ouled Mansour', arabic: 'أولاد منصور'),
      DzCommune(latin: 'Ouled Sidi Brahim', arabic: 'أولاد سيدي ابراهيم'),
      DzCommune(latin: 'Oultem', arabic: 'أولتام'),
      DzCommune(latin: 'Sidi Aïssa', arabic: 'سيدي عيسى'),
      DzCommune(latin: 'Sidi Hadjeres', arabic: 'سيدي هجرس'),
      DzCommune(latin: 'Slim', arabic: 'سليم'),
      DzCommune(latin: 'Souamaa', arabic: 'السوامع'),
      DzCommune(latin: 'Tarmount', arabic: 'تارمونت'),
    ],
  ),

  // 29 — Mascara
  DzWilaya(
    code: '29',
    latinName: 'Mascara',
    arabicName: 'معسكر',
    communes: [
      DzCommune(latin: 'Mascara', arabic: 'معسكر'),
      DzCommune(latin: 'Aïn Fares', arabic: 'عين فارس'),
      DzCommune(latin: 'Aïn Ferah', arabic: 'عين فراح'),
      DzCommune(latin: 'Aïn Fekan', arabic: 'عين فكان'),
      DzCommune(latin: 'Aouf', arabic: 'عوف'),
      DzCommune(latin: 'Benian', arabic: 'بنيان'),
      DzCommune(latin: 'Bou Hanifia', arabic: 'بوحنيفية'),
      DzCommune(latin: 'Bou Henni', arabic: 'بو حني'),
      DzCommune(latin: 'El Bordj', arabic: 'البرج'),
      DzCommune(latin: 'El Ghomri', arabic: 'الغوالمري/الغمر؟'), // variantes
      DzCommune(latin: 'El Gueitena', arabic: 'الڤيطنة'),
      DzCommune(latin: 'El Keurt', arabic: 'الكرت'),
      DzCommune(latin: 'Froha', arabic: 'الفراهنية'),
      DzCommune(latin: 'Gharrous', arabic: 'غرّوس'),
      DzCommune(latin: 'Ghriss', arabic: 'غريس'),
      DzCommune(latin: 'Guerni', arabic: 'ڤيرني'),
      DzCommune(latin: 'Hacine', arabic: 'حسين'),
      DzCommune(latin: 'Hachem', arabic: 'هاشم'),
      DzCommune(latin: 'Khalouia', arabic: 'خلوية'),
      DzCommune(latin: 'Maoussa', arabic: 'ماوسة'),
      DzCommune(latin: 'Matemore', arabic: 'مطمور'),
      DzCommune(latin: 'Mocta Douz', arabic: 'مقطع الدوز'),
      DzCommune(latin: 'Nesmot', arabic: 'نسموط'),
      DzCommune(latin: 'Oggaz', arabic: 'عقاز'),
      DzCommune(latin: 'Ouled Attia', arabic: 'أولاد عطية'),
      DzCommune(latin: 'Ras El Ain Amirouche', arabic: 'رأس العين عميروش'),
      DzCommune(latin: 'Sedjerara', arabic: 'سجرارة'),
      DzCommune(latin: 'Sehailia', arabic: 'سحيلية'),
      DzCommune(latin: 'Sidi Abdeldjebar', arabic: 'سيدي عبد الجبار'),
      DzCommune(latin: 'Sidi Abdelmoumen', arabic: 'سيدي عبد المؤمن'),
      DzCommune(latin: 'Sidi Kada', arabic: 'سيدي قادة'),
      DzCommune(latin: 'Sig', arabic: 'سيق'),
      DzCommune(latin: 'Tighennif', arabic: 'تيغنيف'),
      DzCommune(latin: 'Zahana', arabic: 'زahana/زهانة'),
      DzCommune(latin: 'Zelmata', arabic: 'زلمطة'),
    ],
  ),

  // 30 — Ouargla
  DzWilaya(
    code: '30',
    latinName: 'Ouargla',
    arabicName: 'ورقلة',
    communes: [
      DzCommune(latin: 'Ouargla', arabic: 'ورقلة'),
      DzCommune(latin: 'Aïn Beida', arabic: 'عين البيضا'),
      DzCommune(latin: 'El Borma', arabic: 'البورمة'),
      DzCommune(latin: 'Hassi Ben Abdellah', arabic: 'حاسي بن عبد الله'),
      DzCommune(latin: 'Hassi Messaoud', arabic: 'حاسي مسعود'),
      DzCommune(latin: 'N’Goussa', arabic: 'نڤوسة'),
      DzCommune(latin: 'Rouissat', arabic: 'رويسات'),
      DzCommune(latin: 'Sidi Khouiled', arabic: 'سيدي خويلد'),
    ],
  ),
];
// lib/data/dz_admin_ar_part7.dart
// Partie 7/?: 31 Oran → 40 Khenchela

const List<DzWilaya> dzWilayasPart7 = [
  // 31 — Oran
  DzWilaya(
    code: '31',
    latinName: 'Oran',
    arabicName: 'وهران',
    communes: [
      DzCommune(latin: 'Oran', arabic: 'وهران'),
      DzCommune(latin: 'Aïn El Turk', arabic: 'عين الترك'),
      DzCommune(latin: 'Arzew', arabic: 'أرزيو'),
      DzCommune(latin: 'Bethioua', arabic: 'بطيوة'),
      DzCommune(latin: 'Bir El Djir', arabic: 'بئر الجير'),
      DzCommune(latin: 'Boufatis', arabic: 'بوفاتيس'),
      DzCommune(latin: 'Bousfer', arabic: 'بوسفر'),
      DzCommune(latin: 'Boutlelis', arabic: 'بوتليليس'),
      DzCommune(latin: 'El Ançor', arabic: 'العنصر'),
      DzCommune(latin: 'El Braya', arabic: 'البراية'),
      DzCommune(latin: 'El Kerma', arabic: 'الكرمة'),
      DzCommune(latin: 'El Karma', arabic: 'الكارما'),
      DzCommune(latin: 'El Messaid', arabic: 'المساعد'),
      DzCommune(latin: 'Es Senia', arabic: 'السانيا'),
      DzCommune(latin: 'Gdyel', arabic: 'قديل'),
      DzCommune(latin: 'Hassi Ben Okba', arabic: 'حاسي بن عقبة'),
      DzCommune(latin: 'Hassi Bounif', arabic: 'حاسي بونيف'),
      DzCommune(latin: 'Mers El Kebir', arabic: 'مرسى الكبير'),
      DzCommune(latin: 'Misserghin', arabic: 'مسرغين'),
      DzCommune(latin: 'Sidi Ben Yebka', arabic: 'سيدي بن يبقى'),
      DzCommune(latin: 'Sidi Chami', arabic: 'سيدي الشحمي'),
      DzCommune(latin: 'Tafraoui', arabic: 'طفراوي'),
    ],
  ),

  // 32 — El Bayadh
  DzWilaya(
    code: '32',
    latinName: 'El Bayadh',
    arabicName: 'البيض',
    communes: [
      DzCommune(latin: 'El Bayadh', arabic: 'البيض'),
      DzCommune(latin: 'Aïn El Orak', arabic: 'عين العراك'),
      DzCommune(latin: 'Arbaouat', arabic: 'أربوات'),
      DzCommune(latin: 'Boualem', arabic: 'بوعلام'),
      DzCommune(latin: 'Bougtoub', arabic: 'بوقطب'),
      DzCommune(latin: 'Boussemghoun', arabic: 'بوسمغون'),
      DzCommune(latin: 'Brezina', arabic: 'بريزينة'),
      DzCommune(latin: 'Cheguig', arabic: 'الشقيق'),
      DzCommune(latin: 'Chellala', arabic: 'شلالة'),
      DzCommune(latin: 'El Abiodh Sidi Cheikh', arabic: 'الأبيض سيدي الشيخ'),
      DzCommune(latin: 'El Bnoud', arabic: 'البنود'),
      DzCommune(latin: 'Ghassoul', arabic: 'الغاسول'),
      DzCommune(latin: 'Kef El Ahmar', arabic: 'الكاف الأحمر'),
      DzCommune(latin: 'Rogassa', arabic: 'رقاصة'),
      DzCommune(latin: 'Sidi Ameur', arabic: 'سيدي عامر'),
      DzCommune(latin: 'Sidi Slimane', arabic: 'سيدي سليمان'),
      DzCommune(latin: 'Stitten', arabic: 'ستيتن'),
    ],
  ),

  // 33 — Illizi
  DzWilaya(
    code: '33',
    latinName: 'Illizi',
    arabicName: 'إليزي',
    communes: [
      DzCommune(latin: 'Illizi', arabic: 'إليزي'),
      DzCommune(latin: 'In Amenas', arabic: 'إن أمناس'),
      DzCommune(latin: 'Debdeb', arabic: 'دداب'),
      DzCommune(latin: 'Bordj Omar Driss', arabic: 'برج عمر إدريس'),
    ],
  ),

  // 34 — Bordj Bou Arreridj
  DzWilaya(
    code: '34',
    latinName: 'Bordj Bou Arreridj',
    arabicName: 'برج بوعريريج',
    communes: [
      DzCommune(latin: 'Bordj Bou Arreridj', arabic: 'برج بوعريريج'),
      DzCommune(latin: 'Aïn Taghrout', arabic: 'عين تاغروت'),
      DzCommune(latin: 'Aïn Tesra', arabic: 'عين تسرة'),
      DzCommune(latin: 'Belimour', arabic: 'بليمور'),
      DzCommune(latin: 'Ben Daoud', arabic: 'بن داود'),
      DzCommune(latin: 'Beni Lahcene', arabic: 'بني لحسن'),
      DzCommune(latin: 'Bordj Ghedir', arabic: 'برج الغدير'),
      DzCommune(latin: 'Bordj Zemoura', arabic: 'برج زمورة'),
      DzCommune(latin: 'Colla', arabic: 'قلالة'),
      DzCommune(latin: 'Djaafra', arabic: 'جعافرة'),
      DzCommune(latin: 'El Ach', arabic: 'العش'),
      DzCommune(latin: 'El Anceur', arabic: 'العناصر'),
      DzCommune(latin: 'El Hamadia', arabic: 'الحمادية'),
      DzCommune(latin: 'El Main', arabic: 'الماين'),
      DzCommune(latin: 'El M\'hir', arabic: 'المهير'),
      DzCommune(latin: 'Ghilassa', arabic: 'غيلاسة'),
      DzCommune(latin: 'Haraza', arabic: 'هرازة'),
      DzCommune(latin: 'Hasnaoua', arabic: 'حسناوة'),
      DzCommune(latin: 'Khelil', arabic: 'خليل'),
      DzCommune(latin: 'Ksour', arabic: 'القصور'),
      DzCommune(latin: 'Mansoura', arabic: 'المنصورة'),
      DzCommune(latin: 'Medjana', arabic: 'مجّانة'),
      DzCommune(latin: 'Ouled Brahem', arabic: 'أولاد ابراهيم'),
      DzCommune(latin: 'Ouled Dahmane', arabic: 'أولاد دحمان'),
      DzCommune(latin: 'Ouled Sidi Brahim', arabic: 'أولاد سيدي ابراهيم'),
      DzCommune(latin: 'Rabta', arabic: 'الرابطة'),
      DzCommune(latin: 'Sidi Embarek', arabic: 'سيدي مبارك'),
      DzCommune(latin: 'Taglait', arabic: 'تاقلعت'),
      DzCommune(latin: 'Tassamert', arabic: 'تاسمرت'),
      DzCommune(latin: 'Teniet En Nasr', arabic: 'ثنية النصر'),
      DzCommune(latin: 'Tesra', arabic: 'تسرة'),
      DzCommune(latin: 'Tefreg', arabic: 'تفرق'),
    ],
  ),

  // 35 — Boumerdès
  DzWilaya(
    code: '35',
    latinName: 'Boumerdès',
    arabicName: 'بومرداس',
    communes: [
      DzCommune(latin: 'Boumerdès', arabic: 'بومرداس'),
      DzCommune(latin: 'Afir', arabic: 'أفير'),
      DzCommune(latin: 'Ammal', arabic: 'عمال'),
      DzCommune(latin: 'Baghlia', arabic: 'بغلية'),
      DzCommune(latin: 'Ben Choud', arabic: 'بن شود'),
      DzCommune(latin: 'Beni Amrane', arabic: 'بني عمران'),
      DzCommune(latin: 'Beni Aïcha', arabic: 'بني عائشة'),
      DzCommune(latin: 'Boudouaou', arabic: 'بودواو'),
      DzCommune(latin: 'Boudouaou El Bahri', arabic: 'بودواو البحري'),
      DzCommune(latin: 'Bouzegza Keddara', arabic: 'بوزقزة قدارة'),
      DzCommune(latin: 'Chabet El Ameur', arabic: 'شعبة العامر'),
      DzCommune(latin: 'Corso', arabic: 'قورصو'),
      DzCommune(latin: 'Dellys', arabic: 'دلس'),
      DzCommune(latin: 'Djinet', arabic: 'جنات'),
      DzCommune(latin: 'El Kharrouba', arabic: 'الخروبة'),
      DzCommune(latin: 'Hammedi', arabic: 'حمادي'),
      DzCommune(latin: 'Issers', arabic: 'يسر'),
      DzCommune(latin: 'Khemis El Khechna', arabic: 'خميس الخشنة'),
      DzCommune(latin: 'Larbatache', arabic: 'الأربعطاش'),
      DzCommune(latin: 'Leghata', arabic: 'لقاطة'),
      DzCommune(latin: 'Naciria', arabic: 'نصيرية'),
      DzCommune(latin: 'Ouled Aïssa', arabic: 'أولاد عيسى'),
      DzCommune(latin: 'Ouled Hedadj', arabic: 'أولاد هداج'),
      DzCommune(latin: 'Ouled Moussa', arabic: 'أولاد موسى'),
      DzCommune(latin: 'Si Mustapha', arabic: 'سي مصطفى'),
      DzCommune(latin: 'Sidi Daoud', arabic: 'سيدي داود'),
      DzCommune(latin: 'Souk El Had', arabic: 'سوق الحد'),
      DzCommune(latin: 'Taourga', arabic: 'تاورقة'),
      DzCommune(latin: 'Thénia', arabic: 'الثنية'),
      DzCommune(latin: 'Tidjelabine', arabic: 'تيجلابين'),
      DzCommune(latin: 'Timezrit', arabic: 'تيمزريت'),
      DzCommune(latin: 'Zemmouri', arabic: 'زموري'),
    ],
  ),

  // 36 — El Tarf
  DzWilaya(
    code: '36',
    latinName: 'El Tarf',
    arabicName: 'الطارف',
    communes: [
      DzCommune(latin: 'El Tarf', arabic: 'الطارف'),
      DzCommune(latin: 'Aïn El Assel', arabic: 'عين العسل'),
      DzCommune(latin: 'Asfour', arabic: 'عصفور'),
      DzCommune(latin: 'Ben Mehidi', arabic: 'بن مهيدي'),
      DzCommune(latin: 'Besbes', arabic: 'البسباس'),
      DzCommune(latin: 'Berrihane', arabic: 'بريحان'),
      DzCommune(latin: 'Bougarra', arabic: 'بوقرة'),
      DzCommune(latin: 'Bouhadjar', arabic: 'بوحجار'),
      DzCommune(latin: 'Bouteldja', arabic: 'بوثلجة'),
      DzCommune(latin: 'Chebaita Mokhtar', arabic: 'شبايطة مختار'),
      DzCommune(latin: 'Chefia', arabic: 'الشافية'),
      DzCommune(latin: 'Chihani', arabic: 'الشهايني'),
      DzCommune(latin: 'Drean', arabic: 'الذرعان'),
      DzCommune(latin: 'El Aioun', arabic: 'العيون'),
      DzCommune(latin: 'El Kala', arabic: 'القالة'),
      DzCommune(latin: 'Hammam Beni Salah', arabic: 'حمام بني صالح'),
      DzCommune(latin: 'Lac Des Oiseaux', arabic: 'بحيرة الطيور'),
      DzCommune(latin: 'Oued Zitoun', arabic: 'وادي الزيتون'),
      DzCommune(latin: 'Raml Souk', arabic: 'رمل السوق'),
      DzCommune(latin: 'Souarekh', arabic: 'السوارخ'),
      DzCommune(latin: 'Zerizer', arabic: 'زريزر'),
      DzCommune(latin: 'Zitouna', arabic: 'الزيتونة'),
    ],
  ),

  // 37 — Tindouf
  DzWilaya(
    code: '37',
    latinName: 'Tindouf',
    arabicName: 'تندوف',
    communes: [
      DzCommune(latin: 'Tindouf', arabic: 'تندوف'),
      DzCommune(latin: 'Oum El Assel', arabic: 'أم العسل'),
    ],
  ),

  // 38 — Tissemsilt
  DzWilaya(
    code: '38',
    latinName: 'Tissemsilt',
    arabicName: 'تيسمسيلت',
    communes: [
      DzCommune(latin: 'Tissemsilt', arabic: 'تيسمسيلت'),
      DzCommune(latin: 'Ammari', arabic: 'عماري'),
      DzCommune(latin: 'Beni Chaib', arabic: 'بني شعيب'),
      DzCommune(latin: 'Beni Lahcene', arabic: 'بني لحسن'),
      DzCommune(latin: 'Bordj Bounaama', arabic: 'برج بونعامة'),
      DzCommune(
        latin: 'Bordj El Emir Abdelkader',
        arabic: 'برج الأمير عبد القادر',
      ),
      DzCommune(latin: 'Bou Caid', arabic: 'بوقايد'),
      DzCommune(latin: 'Khemisti', arabic: 'خميستي'),
      DzCommune(
        latin: 'Lardjem',
        arabic: 'الأربعاء/لرجام',
      ), // لرجام شائع محليًا
      DzCommune(latin: 'Lazharia', arabic: 'الأزهرية'),
      DzCommune(latin: 'Layoune', arabic: 'العيون'),
      DzCommune(latin: 'Maacem', arabic: 'المعاصم'),
      DzCommune(latin: 'Ouled Bessem', arabic: 'أولاد بسام'),
      DzCommune(latin: 'Sidi Abed', arabic: 'سيدي عابد'),
      DzCommune(latin: 'Sidi Boutouchent', arabic: 'سيدي بوتوشنت'),
      DzCommune(latin: 'Sidi Lantri', arabic: 'سيدي العنصري'),
      DzCommune(latin: 'Sidi Slimane', arabic: 'سيدي سليمان'),
      DzCommune(latin: 'Theniet El Had', arabic: 'ثنية الحد'),
      DzCommune(latin: 'Youssoufia', arabic: 'اليوسفية'),
    ],
  ),

  // 39 — El Oued
  DzWilaya(
    code: '39',
    latinName: 'El Oued',
    arabicName: 'الوادي',
    communes: [
      DzCommune(latin: 'El Oued', arabic: 'الوادي'),
      DzCommune(latin: 'Bayadha', arabic: 'البياضة'),
      DzCommune(latin: 'Ben Guecha', arabic: 'بن قشة'),
      DzCommune(latin: 'Debila', arabic: 'الدبيلة'),
      DzCommune(latin: 'Douar El Maa', arabic: 'دوار الماء'),
      DzCommune(latin: 'Guemar', arabic: 'قمار'),
      DzCommune(latin: 'Hassi Khalifa', arabic: 'حاسي خليفة'),
      DzCommune(latin: 'Kouinine', arabic: 'كوينين'),
      DzCommune(latin: 'Magrane', arabic: 'المقرن'),
      DzCommune(latin: 'Mih Ouansa', arabic: 'ميه وانسة'),
      DzCommune(latin: 'Nakhla', arabic: 'النخلة'),
      DzCommune(latin: 'Oued El Alenda', arabic: 'وادي العلندة'),
      DzCommune(latin: 'Reguiba', arabic: 'الرقيبة'),
      DzCommune(latin: 'Robbah', arabic: 'الرُبّاح'),
      DzCommune(latin: 'Sidi Aoun', arabic: 'سيدي عون'),
      DzCommune(latin: 'Taghzout', arabic: 'تاغزوت'),
      DzCommune(latin: 'Taleb Larbi', arabic: 'طالب العربي'),
      DzCommune(
        latin: 'Trifaoui',
        arabic: 'طرفةاوي/طريق فواي',
      ), // variantes d’orthographe
      DzCommune(latin: 'Ourmes', arabic: 'أورمس'),
      DzCommune(latin: 'El Ogla', arabic: 'الأقلى'),
      DzCommune(
        latin: 'El M\'Ghair*',
        arabic: 'المغير*',
      ), // *restructuration récente (wilaya 57)
      DzCommune(
        latin: 'El Oued El M\'Oued',
        arabic: 'الوادي الموعض؟',
      ), // si nécessaire, ajuste
      DzCommune(latin: 'Sidi Amor', arabic: 'سيدي عامر'),
      DzCommune(latin: 'Oum Touyour*', arabic: 'أم طيور*'), // *vers wilaya 57
      DzCommune(latin: 'Still*', arabic: 'سطل*'), // *vers wilaya 57
    ],
  ),

  // 40 — Khenchela
  DzWilaya(
    code: '40',
    latinName: 'Khenchela',
    arabicName: 'خنشلة',
    communes: [
      DzCommune(latin: 'Khenchela', arabic: 'خنشلة'),
      DzCommune(latin: 'Aïn Touila', arabic: 'عين التويلة'),
      DzCommune(latin: 'Baghai', arabic: 'بغاي'),
      DzCommune(latin: 'Babar', arabic: 'بابار'),
      DzCommune(latin: 'Bouhmama', arabic: 'بوحمامة'),
      DzCommune(latin: 'Chelia', arabic: 'الشلية'),
      DzCommune(latin: 'Chechar', arabic: 'ششار'),
      DzCommune(latin: 'Djellal', arabic: 'جلال'),
      DzCommune(latin: 'El Hamma', arabic: 'الحامة'),
      DzCommune(latin: 'El Mahmal', arabic: 'المحمل'),
      DzCommune(latin: 'Ensigha', arabic: 'أنسيغة'),
      DzCommune(latin: 'Kais', arabic: 'قايس'),
      DzCommune(latin: 'Khirane', arabic: 'خيران'),
      DzCommune(latin: 'M\'Toussa', arabic: 'متوسة'),
      DzCommune(latin: 'Remila', arabic: 'الرميلة'),
      DzCommune(latin: 'Tamza', arabic: 'تامزة'),
      DzCommune(latin: 'Yabous', arabic: 'يابوس'),
    ],
  ),
];
// lib/data/dz_admin_ar_part8.dart
// Partie 8/?: 41 Souk Ahras → 50 Bordj Badji Mokhtar
// Réutilise les classes DzCommune et DzWilaya déjà définies.

const List<DzWilaya> dzWilayasPart8 = [
  // 41 — Souk Ahras
  DzWilaya(
    code: '41',
    latinName: 'Souk Ahras',
    arabicName: 'سوق أهراس',
    communes: [
      DzCommune(latin: 'Souk Ahras', arabic: 'سوق أهراس'),
      DzCommune(latin: 'Aïn Soltane', arabic: 'عين سلطان'),
      DzCommune(latin: 'Aïn Zana', arabic: 'عين الزانة'),
      DzCommune(latin: 'Bir Bouhouche', arabic: 'بئر بوحوش'),
      DzCommune(latin: 'Drea', arabic: 'الدريعة'),
      DzCommune(latin: 'El Khmouda', arabic: 'الخماودة'),
      DzCommune(latin: 'Hanancha', arabic: 'الحنانشة'),
      DzCommune(latin: 'Heddada', arabic: 'الحدادة'),
      DzCommune(latin: 'Khedara', arabic: 'الخضارة'),
      DzCommune(latin: 'Machroha', arabic: 'المشروحة'),
      DzCommune(latin: 'M\'Daourouch', arabic: 'مداوروش'),
      DzCommune(latin: 'Merahna', arabic: 'المراهنة'),
      DzCommune(latin: 'Oued Keberit', arabic: 'وادي الكبريت'),
      DzCommune(latin: 'Ouillen', arabic: 'ويلان'),
      DzCommune(latin: 'Ouled Driss', arabic: 'أولاد إدريس'),
      DzCommune(latin: 'Ouled Moumen', arabic: 'أولاد مؤمن'),
      DzCommune(latin: 'Ragouba', arabic: 'الرڤوبة'),
      DzCommune(latin: 'Sedrata', arabic: 'سدراتة'),
      DzCommune(latin: 'Sidi Fredj', arabic: 'سيدي فرج'),
      DzCommune(latin: 'Taoura', arabic: 'تاورة'),
      DzCommune(latin: 'Tiffech', arabic: 'تيڤّش'),
      DzCommune(latin: 'Zaarouria', arabic: 'الزعروية'),
    ],
  ),

  // 42 — Tipaza
  DzWilaya(
    code: '42',
    latinName: 'Tipaza',
    arabicName: 'تيبازة',
    communes: [
      DzCommune(latin: 'Tipaza', arabic: 'تيبازة'),
      DzCommune(latin: 'Aghbal', arabic: 'أغبال'),
      DzCommune(latin: 'Ahmar El Ain', arabic: 'أحمر العين'),
      DzCommune(latin: 'Aïn Tagourait', arabic: 'عين تڤرات'),
      DzCommune(latin: 'Beni Milleuk', arabic: 'بني مليك'),
      DzCommune(latin: 'Bou Ismail', arabic: 'بواسماعيل'),
      DzCommune(latin: 'Bou Haroun', arabic: 'بوهارون'),
      DzCommune(latin: 'Bou Medfaa', arabic: 'بومدفع'),
      DzCommune(latin: 'Cherchell', arabic: 'شرشال'),
      DzCommune(latin: 'Damous', arabic: 'داموس'),
      DzCommune(latin: 'Douaouda', arabic: 'دواودة'),
      DzCommune(latin: 'Fouka', arabic: 'فوكة'),
      DzCommune(latin: 'Gouraya', arabic: 'قوراية'),
      DzCommune(latin: 'Hadjeret Ennous', arabic: 'حجرة النص'),
      DzCommune(latin: 'Hadjout', arabic: 'حجوط'),
      DzCommune(latin: 'Khemisti', arabic: 'خميستي'),
      DzCommune(latin: 'Koléa', arabic: 'القليعة'),
      DzCommune(latin: 'Larhat', arabic: 'الارهاط'),
      DzCommune(
        latin: 'Menaceur',
        arabic: 'منصاع/منصور؟',
      ), // selon source locale "منصاع" أو "منصور"
      DzCommune(latin: 'Merad', arabic: 'مراد'),
      DzCommune(latin: 'Messelmoun', arabic: 'مسلمون'),
      DzCommune(latin: 'Nador', arabic: 'الناظور'),
      DzCommune(latin: 'Sidi Amar', arabic: 'سيدي عامر'),
      DzCommune(latin: 'Sidi Ghiles', arabic: 'سيدي غيليس'),
      DzCommune(latin: 'Sidi Rached', arabic: 'سيدي راشد'),
      DzCommune(latin: 'Sidi Semiane', arabic: 'سيدي سميان'),
    ],
  ),

  // 43 — Mila
  DzWilaya(
    code: '43',
    latinName: 'Mila',
    arabicName: 'ميلة',
    communes: [
      DzCommune(latin: 'Mila', arabic: 'ميلة'),
      DzCommune(latin: 'Aïn Beida Harriche', arabic: 'عين البيضاء حريش'),
      DzCommune(latin: 'Aïn Mellouk', arabic: 'عين ملوك'),
      DzCommune(latin: 'Aïn Tine', arabic: 'عين التين'),
      DzCommune(latin: 'Ahmed Rachedi', arabic: 'أحمد راشدي'),
      DzCommune(latin: 'Amira Arras', arabic: 'عميرة أراس'),
      DzCommune(latin: 'Bouhatem', arabic: 'بوحاتم'),
      DzCommune(latin: 'Chelghoum Laïd', arabic: 'شلغوم العيد'),
      DzCommune(latin: 'Chigara', arabic: 'شيقارة'),
      DzCommune(latin: 'Derradji Bousselah', arabic: 'دراجى بوصلاح'),
      DzCommune(latin: 'El Mechira', arabic: 'المشيرة'),
      DzCommune(latin: 'Elayadi Barbes', arabic: 'العياشي برباس'),
      DzCommune(latin: 'Ferdjioua', arabic: 'فرجيوة'),
      DzCommune(latin: 'Grarem Gouga', arabic: 'قرارم ڤوڤة'),
      DzCommune(latin: 'Hamala', arabic: 'حمالة'),
      DzCommune(latin: 'Minar Zarza', arabic: 'مينار زارزة'),
      DzCommune(latin: 'Oued Athmenia', arabic: 'وادي العثمانية'),
      DzCommune(latin: 'Oued Endja', arabic: 'وادي النجاء'),
      DzCommune(latin: 'Ouled Khalouf', arabic: 'أولاد خلوف'),
      DzCommune(latin: 'Rouached', arabic: 'رواشد'),
      DzCommune(latin: 'Sidi Khelifa', arabic: 'سيدي خليفة'),
      DzCommune(latin: 'Tadjenanet', arabic: 'تاجنانت'),
      DzCommune(latin: 'Tassadane Haddada', arabic: 'تسدان حدادة'),
      DzCommune(latin: 'Teleghma', arabic: 'تلاغمة'),
      DzCommune(latin: 'Terrai Bainen', arabic: 'ترعي باينان'),
      DzCommune(latin: 'Zeghaia', arabic: 'زغاية'),
    ],
  ),

  // 44 — Aïn Defla
  DzWilaya(
    code: '44',
    latinName: 'Aïn Defla',
    arabicName: 'عين الدفلى',
    communes: [
      DzCommune(latin: 'Aïn Defla', arabic: 'عين الدفلى'),
      DzCommune(latin: 'Aïn Benian', arabic: 'عين بنيان'),
      DzCommune(latin: 'Aïn Bouyahia', arabic: 'عين بويحيى'),
      DzCommune(latin: 'Aïn Lechiakh', arabic: 'عين الاشياخ'),
      DzCommune(latin: 'Aïn Soltane', arabic: 'عين سلطان'),
      DzCommune(latin: 'Arib', arabic: 'عريب'),
      DzCommune(latin: 'Bathia', arabic: 'بطحية'),
      DzCommune(latin: 'Bir Ould Khelifa', arabic: 'بئر ولد خليفة'),
      DzCommune(latin: 'Bordj Emir Khaled', arabic: 'برج الأمير خالد'),
      DzCommune(latin: 'Boumedfaa', arabic: 'بومدفع'),
      DzCommune(latin: 'Bourached', arabic: 'بوراشد'),
      DzCommune(latin: 'Djelida', arabic: 'جليدة'),
      DzCommune(latin: 'Djendel', arabic: 'جندل'),
      DzCommune(latin: 'El Abadia', arabic: 'العبادية'),
      DzCommune(latin: 'El Amra', arabic: 'العَمرة'),
      DzCommune(latin: 'El Attaf', arabic: 'العطاف'),
      DzCommune(latin: 'El Hassania', arabic: 'الحسانية'),
      DzCommune(latin: 'Hammam Righa', arabic: 'حمام ريغة'),
      DzCommune(latin: 'Hoceinia', arabic: 'حسينية'),
      DzCommune(latin: 'Khemis Miliana', arabic: 'خميس مليانة'),
      DzCommune(latin: 'Mekhatria', arabic: 'المخاطرية'),
      DzCommune(latin: 'Miliana', arabic: 'مليانة'),
      DzCommune(latin: 'Oued Djemaa', arabic: 'وادي الجمعة'),
      DzCommune(latin: 'Rouina', arabic: 'روينة'),
      DzCommune(latin: 'Sidi Lakhdar', arabic: 'سيدي لخضر'),
      DzCommune(latin: 'Tacheta Zegagha', arabic: 'تاشتة زڤاغة'),
      DzCommune(latin: 'Tarik Ibn Ziad', arabic: 'طارق بن زياد'),
      DzCommune(latin: 'Zeddine', arabic: 'زدّين'),
    ],
  ),

  // 45 — Naâma
  DzWilaya(
    code: '45',
    latinName: 'Naâma',
    arabicName: 'النعامة',
    communes: [
      DzCommune(latin: 'Naâma', arabic: 'النعامة'),
      DzCommune(latin: 'Aïn Ben Khelil', arabic: 'عين بن خليل'),
      DzCommune(latin: 'Aïn Sefra', arabic: 'عين الصفراء'),
      DzCommune(latin: 'Assela', arabic: 'عسلة'),
      DzCommune(latin: 'Kasdir', arabic: 'القصدير'),
      DzCommune(latin: 'Makman Ben Amer', arabic: 'مكمن بن عمار'),
      DzCommune(latin: 'Mecheria', arabic: 'المشرية'),
      DzCommune(latin: 'Moghrar', arabic: 'مغرار'),
      DzCommune(latin: 'Sfissifa', arabic: 'السفيسيفة'),
      DzCommune(latin: 'Tiout', arabic: 'تيوت'),
    ],
  ),

  // 46 — Aïn Témouchent
  DzWilaya(
    code: '46',
    latinName: 'Aïn Témouchent',
    arabicName: 'عين تموشنت',
    communes: [
      DzCommune(latin: 'Aïn Témouchent', arabic: 'عين تموشنت'),
      DzCommune(latin: 'Aghlal', arabic: 'أغلال'),
      DzCommune(latin: 'Aïn El Arbaa', arabic: 'عين الأربعة'),
      DzCommune(latin: 'Aïn Kihal', arabic: 'عين الكيحل'),
      DzCommune(
        latin: 'Aoubellil',
        arabic: 'عقباليل/عقب الليل',
      ), // variantes locales
      DzCommune(latin: 'Beni Saf', arabic: 'بني صاف'),
      DzCommune(latin: 'Bouzedjar', arabic: 'بوزجار'),
      DzCommune(latin: 'Chentouf', arabic: 'شنتوف'),
      DzCommune(latin: 'El Amria', arabic: 'الأمريّة'),
      DzCommune(latin: 'El Malah', arabic: 'الملاح'),
      DzCommune(latin: 'El Messaid', arabic: 'المساعد'),
      DzCommune(latin: 'Hammam Bouhadjar', arabic: 'حمّام بوحجر'),
      DzCommune(latin: 'Hassi El Ghella', arabic: 'حاسي الغلة'),
      DzCommune(latin: 'Oued Berkeche', arabic: 'وادي برقش'),
      DzCommune(latin: 'Ouled Boudjemaa', arabic: 'أولاد بوجمعة'),
      DzCommune(latin: 'Ouled Kihal', arabic: 'أولاد كيحل'),
      DzCommune(latin: 'Sidi Ben Adda', arabic: 'سيدي بن عدة'),
      DzCommune(latin: 'Sidi Boumediene', arabic: 'سيدي بومدين'),
      DzCommune(latin: 'Sidi Ouriache', arabic: 'سيدي ورياش'),
      DzCommune(latin: 'Tamzoura', arabic: 'تامزورة'),
      DzCommune(latin: 'Terga', arabic: 'تارقة'),
    ],
  ),

  // 47 — Ghardaïa
  DzWilaya(
    code: '47',
    latinName: 'Ghardaïa',
    arabicName: 'غرداية',
    communes: [
      DzCommune(latin: 'Ghardaïa', arabic: 'غرداية'),
      DzCommune(latin: 'Berriane', arabic: 'بريان'),
      DzCommune(latin: 'Bounoura', arabic: 'بونورة'),
      DzCommune(latin: 'Dhayet Bendhahoua', arabic: 'ضاية بن ضحوة'),
      DzCommune(latin: 'El Atteuf', arabic: 'العطف'),
      DzCommune(latin: 'El Guerrara', arabic: 'القرارة'),
      DzCommune(latin: 'Mansoura', arabic: 'المنصورة'),
      DzCommune(latin: 'Metlili', arabic: 'متليلي'),
    ],
  ),

  // 48 — Relizane
  DzWilaya(
    code: '48',
    latinName: 'Relizane',
    arabicName: 'غليزان',
    communes: [
      DzCommune(latin: 'Relizane', arabic: 'غليزان'),
      DzCommune(latin: 'Aïn Rahma', arabic: 'عين الرحمة'),
      DzCommune(latin: 'Aïn Tarek', arabic: 'عين طارق'),
      DzCommune(latin: 'Ammi Moussa', arabic: 'عمي موسى'),
      DzCommune(latin: 'Belaassel Bouzagza', arabic: 'بلعسل بوزڤزة'),
      DzCommune(latin: 'Bendaoud', arabic: 'بن داود'),
      DzCommune(latin: 'Beni Dergoun', arabic: 'بني درقون'),
      DzCommune(latin: 'Beni Zentis', arabic: 'بني زنطيس'),
      DzCommune(latin: 'Dar Ben Abdelah', arabic: 'دار بن عبد الله'),
      DzCommune(latin: 'Djidiouia', arabic: 'جديوية'),
      DzCommune(latin: 'El Guettar', arabic: 'الڤطار'),
      DzCommune(latin: 'El Hassi', arabic: 'الحاسي'),
      DzCommune(latin: 'El Matmar', arabic: 'المطمر'),
      DzCommune(latin: 'El Ouldja', arabic: 'الولجة'),
      DzCommune(latin: 'Had Echkalla', arabic: 'حد اشكالة'),
      DzCommune(latin: 'Hamri', arabic: 'حمري'),
      DzCommune(latin: 'Kalaa', arabic: 'القلعة'),
      DzCommune(latin: 'Lahlef', arabic: 'لهلف'),
      DzCommune(latin: 'Mazouna', arabic: 'مازونة'),
      DzCommune(latin: 'Mediouna', arabic: 'ميديونة'),
      DzCommune(latin: 'Mendes', arabic: 'منداس'),
      DzCommune(latin: 'Oued Essalem', arabic: 'وادي السلام'),
      DzCommune(latin: 'Ouarizane', arabic: 'وارزان'),
      DzCommune(latin: 'Ouled Aiche', arabic: 'أولاد عيش'),
      DzCommune(latin: 'Ouled Sidi Mihoub', arabic: 'أولاد سيدي ميهوب'),
      DzCommune(latin: 'Ramka', arabic: 'رمقة'),
      DzCommune(latin: 'Sidi Khettab', arabic: 'سيدي خطاب'),
      DzCommune(latin: 'Sidi Lazreg', arabic: 'سيدي لازرق'),
      DzCommune(latin: 'Sidi M’Hamed Benaouda', arabic: 'سيدي محمد بن عودة'),
      DzCommune(latin: 'Souk El Had', arabic: 'سوق الحد'),
      DzCommune(latin: 'Yellel', arabic: 'يلل'),
      DzCommune(latin: 'Zemmoura', arabic: 'زمورة'),
    ],
  ),

  // 49 — Timimoun (nouvelle wilaya)
  DzWilaya(
    code: '49',
    latinName: 'Timimoun',
    arabicName: 'تيميمون',
    communes: [
      DzCommune(latin: 'Timimoun', arabic: 'تيميمون'),
      DzCommune(latin: 'Aougrout', arabic: 'أوقروت'),
      DzCommune(latin: 'Charouine', arabic: 'شروين'),
      DzCommune(latin: 'Deldoul', arabic: 'دلدول'),
      DzCommune(latin: 'Ksar Kaddour', arabic: 'قصر قدور'),
      DzCommune(latin: 'Ouled Said', arabic: 'أولاد السعيد'),
      DzCommune(latin: 'Talmine', arabic: 'تالمين'),
      DzCommune(latin: 'Tinerkouk', arabic: 'تينركوك'),
    ],
  ),

  // 50 — Bordj Badji Mokhtar (nouvelle wilaya)
  DzWilaya(
    code: '50',
    latinName: 'Bordj Badji Mokhtar',
    arabicName: 'برج باجي مختار',
    communes: [
      DzCommune(latin: 'Bordj Badji Mokhtar', arabic: 'برج باجي مختار'),
    ],
  ),
];

// lib/data/dz_admin_ar_part9.dart
// Partie 9/9 : 51 Ouled Djellal → 58 El Meniaa
// Réutilise les classes DzCommune et DzWilaya déjà déclarées.

const List<DzWilaya> dzWilayasPart9 = [
  // 51 — Ouled Djellal
  DzWilaya(
    code: '51',
    latinName: 'Ouled Djellal',
    arabicName: 'أولاد جلال',
    communes: [
      DzCommune(latin: 'Ouled Djellal', arabic: 'أولاد جلال'),
      DzCommune(latin: 'Besbes', arabic: 'بسـبـس'),
      DzCommune(latin: 'Chaiba', arabic: 'الشعيبة'),
      DzCommune(latin: 'Doucen', arabic: 'دوسن'),
      DzCommune(latin: 'Ras El Miad', arabic: 'رأس الميعاد'),
      DzCommune(latin: 'Sidi Khaled', arabic: 'سيدي خالد'),
    ],
  ),

  // 52 — Béni Abbès
  DzWilaya(
    code: '52',
    latinName: 'Béni Abbès',
    arabicName: 'بني عباس',
    communes: [
      DzCommune(latin: 'Béni Abbès', arabic: 'بني عباس'),
      DzCommune(latin: 'El Ouata', arabic: 'العواطة'),
      DzCommune(latin: 'Igli', arabic: 'إقلي'),
      DzCommune(latin: 'Kerzaz', arabic: 'كرزاز'),
      DzCommune(latin: 'Ksabi', arabic: 'القصابي'),
      DzCommune(latin: 'Ouled Khoudir', arabic: 'أولاد خضير'),
      DzCommune(latin: 'Tamtert', arabic: 'تامترت'),
      DzCommune(latin: 'Tabelbala', arabic: 'تبلبالة'),
      DzCommune(latin: 'El Bnoud', arabic: 'البنود'),
    ],
  ),

  // 53 — In Salah
  DzWilaya(
    code: '53',
    latinName: 'In Salah',
    arabicName: 'عين صالح',
    communes: [
      DzCommune(latin: 'In Salah', arabic: 'عين صالح'),
      DzCommune(latin: 'Foggaret Ezzoua', arabic: 'فقارة الزوا'),
      DzCommune(latin: 'Ain Salah Nord', arabic: 'عين صالح شمال'),
      DzCommune(latin: 'Ain Salah Sud', arabic: 'عين صالح جنوب'),
    ],
  ),

  // 54 — In Guezzam
  DzWilaya(
    code: '54',
    latinName: 'In Guezzam',
    arabicName: 'عين قزام',
    communes: [
      DzCommune(latin: 'In Guezzam', arabic: 'عين قزام'),
      DzCommune(latin: 'Tin Zaouatine', arabic: 'تين زواتين'),
    ],
  ),

  // 55 — Touggourt
  DzWilaya(
    code: '55',
    latinName: 'Touggourt',
    arabicName: 'تقرت',
    communes: [
      DzCommune(latin: 'Touggourt', arabic: 'تقرت'),
      DzCommune(latin: 'Nezla', arabic: 'النزلة'),
      DzCommune(latin: 'Tamacine', arabic: 'تماسين'),
      DzCommune(latin: 'Meggarine', arabic: 'المقارين'),
      DzCommune(latin: 'Sidi Slimane', arabic: 'سيدي سليمان'),
      DzCommune(latin: 'Blidet Amor', arabic: 'بلدة عامر'),
      DzCommune(latin: 'El Hadjira', arabic: 'الحجيرة'),
      DzCommune(latin: 'Ouargla Nord', arabic: 'ورقلة شمال'),
      DzCommune(latin: 'Ouargla Sud', arabic: 'ورقلة جنوب'),
    ],
  ),

  // 56 — Djanet
  DzWilaya(
    code: '56',
    latinName: 'Djanet',
    arabicName: 'جانت',
    communes: [
      DzCommune(latin: 'Djanet', arabic: 'جانت'),
      DzCommune(latin: 'Bordj El Haouas', arabic: 'برج الحواس'),
    ],
  ),

  // 57 — El M’Ghair
  DzWilaya(
    code: '57',
    latinName: 'El M’Ghair',
    arabicName: 'المغير',
    communes: [
      DzCommune(latin: 'El M’Ghair', arabic: 'المغير'),
      DzCommune(latin: 'Djamaa', arabic: 'جامعة'),
      DzCommune(latin: 'El M’Ghayer', arabic: 'المـڤاير'),
      DzCommune(latin: 'El M’Rara', arabic: 'المراّرة'),
      DzCommune(latin: 'Mih Ouansa', arabic: 'ميه وانسة'),
      DzCommune(latin: 'Oum Touyour', arabic: 'أم الطيور'),
      DzCommune(latin: 'Sidi Khelil', arabic: 'سيدي خليل'),
      DzCommune(latin: 'Still', arabic: 'سطل'),
      DzCommune(latin: 'Tenedla', arabic: 'تندلة'),
    ],
  ),

  // 58 — El Meniaa
  DzWilaya(
    code: '58',
    latinName: 'El Meniaa',
    arabicName: 'المنيعة',
    communes: [
      DzCommune(latin: 'El Meniaa', arabic: 'المنيعة'),
      DzCommune(latin: 'Hassi Gara', arabic: 'حاسي قرّة'),
      DzCommune(latin: 'Hassi Fehal', arabic: 'حاسي الفحال'),
    ],
  ),
];

// lib/data/dz_admin_ar_part10.dart
// Partie 10/10 : 59 Aflou → 69 Messaad (nouvelles wilayas)

const List<DzWilaya> dzWilayasPart10 = [
  DzWilaya(
    code: '59',
    latinName: 'Aflou',
    arabicName: 'أفلو',
    communes: const [
      DzCommune(latin: 'Aflou', arabic: 'أفلو'),
    ],
  ),
  DzWilaya(
    code: '60',
    latinName: 'El Abiodh Sidi Cheikh',
    arabicName: 'الأبيض سيدي الشيخ',
    communes: const [
      DzCommune(latin: 'El Abiodh Sidi Cheikh', arabic: 'الأبيض سيدي الشيخ'),
    ],
  ),
  DzWilaya(
    code: '61',
    latinName: 'El Aricha',
    arabicName: 'العريشة',
    communes: const [
      DzCommune(latin: 'El Aricha', arabic: 'العريشة'),
    ],
  ),
  DzWilaya(
    code: '62',
    latinName: 'El Kantara',
    arabicName: 'القنطرة',
    communes: const [
      DzCommune(latin: 'El Kantara', arabic: 'القنطرة'),
    ],
  ),
  DzWilaya(
    code: '63',
    latinName: 'Barika',
    arabicName: 'بريكة',
    communes: const [
      DzCommune(latin: 'Barika', arabic: 'بريكة'),
    ],
  ),
  DzWilaya(
    code: '64',
    latinName: 'Bou Saâda',
    arabicName: 'بوسعادة',
    communes: const [
      DzCommune(latin: 'Bou Saâda', arabic: 'بوسعادة'),
    ],
  ),
  DzWilaya(
    code: '65',
    latinName: 'Bir El Ater',
    arabicName: 'بئر العاتر',
    communes: const [
      DzCommune(latin: 'Bir El Ater', arabic: 'بئر العاتر'),
    ],
  ),
  DzWilaya(
    code: '66',
    latinName: 'Ksar El Boukhari',
    arabicName: 'قصر البخاري',
    communes: const [
      DzCommune(latin: 'Ksar El Boukhari', arabic: 'قصر البخاري'),
    ],
  ),
  DzWilaya(
    code: '67',
    latinName: 'Ksar Chellala',
    arabicName: 'قصر الشلالة',
    communes: const [
      DzCommune(latin: 'Ksar Chellala', arabic: 'قصر الشلالة'),
    ],
  ),
  DzWilaya(
    code: '68',
    latinName: 'Aïn Oussara',
    arabicName: 'عين وسارة',
    communes: const [
      DzCommune(latin: 'Aïn Oussara', arabic: 'عين وسارة'),
    ],
  ),
  DzWilaya(
    code: '69',
    latinName: 'Messaad',
    arabicName: 'مسعد',
    communes: const [
      DzCommune(latin: 'Messaad', arabic: 'مسعد'),
    ],
  ),
];

final List<DzWilaya> dzWilayas = [
  ...dzWilayasPart1,
  ...dzWilayasPart2,
  ...dzWilayasPart3,
  ...dzWilayasPart4,
  ...dzWilayasPart5,
  ...dzWilayasPart6,
  ...dzWilayasPart7,
  ...dzWilayasPart8,
  ...dzWilayasPart9,
  ...dzWilayasPart10,
];
