// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8k-bzu_CpLNYG-KfuH6MivT_jItbTMM',
    appId: '1:884838571648:web:3957e3990c3c74abbb1065',
    messagingSenderId: '884838571648',
    projectId: 'winycar-74cd4',
    authDomain: 'winycar-74cd4.firebaseapp.com',
    storageBucket: 'winycar-74cd4.firebasestorage.app',
    measurementId: 'G-ER6VH7RWSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAfq8T96sJt03i9Rk3feeMjfIprW1K_7w',
    appId: '1:884838571648:android:45ea31418dac7337bb1065',
    messagingSenderId: '884838571648',
    projectId: 'winycar-74cd4',
    storageBucket: 'winycar-74cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2iba12Rq4ge1AaJVPMeuKYo6dx4yNcI',
    appId: '1:884838571648:ios:1fb75efac72eb2d8bb1065',
    messagingSenderId: '884838571648',
    projectId: 'winycar-74cd4',
    storageBucket: 'winycar-74cd4.firebasestorage.app',
    iosBundleId: 'com.winycar.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2iba12Rq4ge1AaJVPMeuKYo6dx4yNcI',
    appId: '1:884838571648:ios:1fb75efac72eb2d8bb1065',
    messagingSenderId: '884838571648',
    projectId: 'winycar-74cd4',
    storageBucket: 'winycar-74cd4.firebasestorage.app',
    iosBundleId: 'com.winycar.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8k-bzu_CpLNYG-KfuH6MivT_jItbTMM',
    appId: '1:884838571648:web:c9d80eccadbb9244bb1065',
    messagingSenderId: '884838571648',
    projectId: 'winycar-74cd4',
    authDomain: 'winycar-74cd4.firebaseapp.com',
    storageBucket: 'winycar-74cd4.firebasestorage.app',
    measurementId: 'G-RWXRHZTCJ9',
  );

}